{{
    config( alias='funcionario',schema='recursos_humanos_ergon_comlurb')
}}

SELECT
    safe_cast(TRIM(flex_campo_10) AS STRING) AS emissor_rne,
    safe_cast(PARSE_DATE("%d/%m/%Y",REGEXP_REPLACE(flex_campo_11, "//", "/")) AS DATE) AS data_expedicao_rne,
    safe_cast(PARSE_DATE("%d/%m/%Y",REGEXP_REPLACE(flex_campo_12, "//", "/")) AS DATE) AS data_chegada_brasil,
    safe_cast(PARSE_DATE("%d/%m/%Y",REGEXP_REPLACE(flex_campo_13, "//", "/")) AS DATE) AS data_naturalizacao,
    safe_cast(TRIM(flex_campo_14) AS STRING) AS casado_brasileiro,
    safe_cast(TRIM(flex_campo_15) AS STRING) AS filho_brasileiro,
    safe_cast(TRIM(flex_campo_90) AS STRING) AS email_alternativo,
    safe_cast(REGEXP_REPLACE(TRIM(numero), r'\.0$', '') AS STRING) AS id_vinculo,
    safe_cast(TRIM(nome) AS STRING) AS nome,
    safe_cast(TRIM(flex_campo_03) AS STRING) AS nome_complementar,
    safe_cast(TRIM(sexo) AS STRING) AS sexo,
    safe_cast(DATE(dtnasc) AS DATE) AS data_nascimento,
    safe_cast(TRIM(flex_campo_16) AS STRING) AS trabalho_voluntario,
    safe_cast(TRIM(flex_campo_17) AS STRING) AS interesse_trabalho_voluntario,
    safe_cast(TRIM(flex_campo_18) AS STRING) AS interesse_projeto_olimpico,
    safe_cast(TRIM(flex_campo_19) AS STRING) AS interesse_projeto_social,
    safe_cast(TRIM(flex_campo_20) AS STRING) AS login_facebook,
    safe_cast(TRIM(flex_campo_21) AS STRING) AS login_twitter,
    safe_cast(TRIM(flex_campo_22) AS STRING) AS login_google_plus,
    safe_cast(TRIM(flex_campo_23) AS STRING) AS login_instagram,
    safe_cast(TRIM(flex_campo_24) AS STRING) AS login_linkedin,
    safe_cast(TRIM(flex_campo_25) AS STRING) AS login_myspace,
    safe_cast(TRIM(flex_campo_26) AS STRING) AS emissor_cnh,
    safe_cast(PARSE_DATE("%d/%m/%Y",REGEXP_REPLACE(flex_campo_27, "//", "/")) AS DATE) AS data_expedicao_cnh,
    safe_cast(PARSE_DATE("%d/%m/%Y",REGEXP_REPLACE(flex_campo_28, "//", "/")) AS DATE) AS data_expedicao_orgao_classe,
    safe_cast(TRIM(flex_campo_30) AS STRING) AS emissor_orgao_classe,
    safe_cast(PARSE_DATE("%d/%m/%Y",REGEXP_REPLACE(flex_campo_36, "//", "/")) AS DATE) AS data_ultima_atualizaca_bancaria,
    safe_cast(REGEXP_REPLACE(TRIM(flex_campo_40), r'\.0$', '') AS STRING) AS id_nis,
    safe_cast(TRIM(raca) AS STRING) AS raca_cor,
    safe_cast(TRIM(deficiente) AS STRING) AS deficiente,
    safe_cast(TRIM(uf_cart) AS STRING) AS sigla_uf_cartorio_certidao_civil,
    safe_cast(TRIM(cidnasc) AS STRING) AS municipio_nascimento,
    safe_cast(TRIM(ufnasc) AS STRING) AS sigla_uf_nascimento,
    safe_cast(TRIM(g_sanguineo) AS STRING) AS grupo_sanguineo,
    safe_cast(TRIM(pai) AS STRING) AS nome_pai,
    safe_cast(TRIM(mae) AS STRING) AS nome_mae,
    safe_cast(REGEXP_REPLACE(TRIM(chegbrasil), r'\.0$', '') AS INT64) AS ano_chegada_brasil,
    safe_cast(TRIM(ufempant) AS STRING) AS sigla_uf_emprego_anterior,
    safe_cast(REGEXP_REPLACE(TRIM(anoprimemp), r'\.0$', '') AS INT64) AS ano_primeiro_emprego,
    safe_cast(REGEXP_REPLACE(TRIM(identprof), r'\.0$', '') AS STRING) AS id_profissional,
    safe_cast(REGEXP_REPLACE(TRIM(flex_campo_06), r'\.0$', '') AS STRING) AS id_ric,
    safe_cast(TRIM(flex_campo_07) AS STRING) AS orgao_ric,
    safe_cast(PARSE_DATE("%d/%m/%Y",REGEXP_REPLACE(flex_campo_08, "//", "/")) AS DATE) AS data_ric,
    safe_cast(REGEXP_REPLACE(TRIM(flex_campo_09), r'\.0$', '') AS STRING) AS id_rne,
    safe_cast(REGEXP_REPLACE(TRIM(numrg), r'\.0$', '') AS STRING) AS id_rg,
    safe_cast(TRIM(tiporg) AS STRING) AS tipo_rg,
    safe_cast(TRIM(orgaorg) AS STRING) AS emissor_rg,
    safe_cast(TRIM(municipio_cart) AS STRING) AS municipio_cartorio_certidao_civil,
    safe_cast(TRIM(tipodoc_cert) AS STRING) AS tipo_certidao_civil,
    safe_cast(TRIM(uf_identprof) AS STRING) AS sigla_uf_orgao_classe,
    safe_cast(DATE(expedrg) AS DATE) AS data_expedicao_rg,
    safe_cast(TRIM(orgaomili) AS STRING) AS emissor_documento_militar,
    safe_cast(TRIM(ufdocmili) AS STRING) AS sigla_uf_documento_militar,
    safe_cast(TRIM(tipodefic) AS STRING) AS tipo_deficiencia,
    safe_cast(TRIM(matricula_cert) AS STRING) AS matricula_certidao,
    safe_cast(TRIM(flex_campo_51) AS STRING) AS deficiencia_fisica,
    safe_cast(TRIM(flex_campo_52) AS STRING) AS deficiencia_visual,
    safe_cast(TRIM(flex_campo_53) AS STRING) AS deficiencia_auditiva,
    safe_cast(TRIM(flex_campo_54) AS STRING) AS deficiencia_mental,
    safe_cast(TRIM(flex_campo_55) AS STRING) AS deficiencia_intelectual,
    safe_cast(TRIM(flex_campo_56) AS STRING) AS recebe_beneficio_previdenciario,
    safe_cast(TRIM(flex_campo_58) AS STRING) AS nome_posse,
    safe_cast(TRIM(flex_campo_59) AS STRING) AS sexo_posse,
    safe_cast(PARSE_DATE("%d/%m/%Y",REGEXP_REPLACE(flex_campo_60, "//", "/")) AS DATE) AS data_alteracao_sexo,
    safe_cast(TRIM(flex_campo_69) AS STRING) AS pais_nascimento,
    safe_cast(PARSE_DATE("%d/%m/%Y",REGEXP_REPLACE(flex_campo_70, "//", "/")) AS DATE) AS data_alteracao,
    safe_cast(REGEXP_REPLACE(TRIM(cpf), r'\.0$', '') AS STRING) AS id_cpf,
    safe_cast(REGEXP_REPLACE(TRIM(numcartpro), r'\.0$', '') AS STRING) AS id_ctps,
    safe_cast(TRIM(sercartpro) AS STRING) AS serie_ctps,
    safe_cast(TRIM(ufcartpro) AS STRING) AS sigla_uf_ctps,
    safe_cast(REGEXP_REPLACE(TRIM(numtitel), r'\.0$', '') AS STRING) AS id_titulo_eleitor,
    safe_cast(TRIM(zonatitel) AS STRING) AS zona_eleitoral,
    safe_cast(TRIM(sectitel) AS STRING) AS secao_eleitoral,
    safe_cast(TRIM(uftitel) AS STRING) AS sigla_uf_titulo_eleitor,
    safe_cast(REGEXP_REPLACE(TRIM(numdocmili), r'\.0$', '') AS STRING) AS id_documento_militar,
    safe_cast(TRIM(serdocmili) AS STRING) AS serie_documento_militar,
    safe_cast(REGEXP_REPLACE(TRIM(cnh), r'\.0$', '') AS STRING) AS id_cnh,
    safe_cast(TRIM(catcnh) AS STRING) AS categoria_cnh,
    safe_cast(DATE(validcnh) AS DATE) AS validade_cnh,
    safe_cast(TRIM(ufcnh) AS STRING) AS sigla_uf_cnh,
    safe_cast(REGEXP_REPLACE(TRIM(pispasep), r'\.0$', '') AS STRING) AS id_pispasep,
    safe_cast(DATE(datapis) AS DATE) AS data_inicio_nis,
    safe_cast(TRIM(bancopis) AS STRING) AS numero_banco_nis,
    safe_cast(TRIM(tipoidprof) AS STRING) AS tipo_identidade_profissional,
    safe_cast(TRIM(tipologender) AS STRING) AS tipo_logradouro,
    safe_cast(TRIM(nomelogender) AS STRING) AS logradouro,
    safe_cast(REGEXP_REPLACE(TRIM(numender), r'\.0$', '') AS INT64) AS numero_porta,
    safe_cast(TRIM(complender) AS STRING) AS complemento_numero_porta,
    safe_cast(TRIM(bairroender) AS STRING) AS bairro,
    safe_cast(TRIM(cidadeender) AS STRING) AS municipio,
    safe_cast(TRIM(ufender) AS STRING) AS sigla_uf,
    safe_cast(TRIM(cepender) AS STRING) AS cep,
    safe_cast(TRIM(telefone) AS STRING) AS telefone,
    safe_cast(TRIM(banco) AS STRING) AS banco,
    safe_cast(TRIM(agencia) AS STRING) AS agencia,
    safe_cast(TRIM(conta) AS STRING) AS conta,
    safe_cast(TRIM(num_cert) AS STRING) AS numero_certidao,
    safe_cast(TRIM(livro_a_cert) AS STRING) AS livro_certidao,
    safe_cast(TRIM(folha_cert) AS STRING) AS folha_certidao,
    safe_cast(TRIM(cartorio_cert) AS STRING) AS cartorio_certidao,
    safe_cast(TRIM(ramal) AS STRING) AS ramal,
    safe_cast(TRIM(tratamento) AS STRING) AS nome_tratamento,
    safe_cast(TRIM(e_mail) AS STRING) AS email,
    safe_cast(TRIM(numtel_celular) AS STRING) AS celular,
    safe_cast(TRIM(flex_campo_02) AS STRING) AS impedimento,
    safe_cast(REGEXP_REPLACE(id_reg, r'\.0$', '') AS STRING) AS id_registro,
    safe_cast(REGEXP_REPLACE(id_pessoa, r'\.0$', '') AS STRING) AS id_pessoa,
    safe_cast(TRIM(nome_busca) AS STRING) AS nome_busca,
    safe_cast(DATE(TRIM(dt_recadast)) AS DATE) AS data_recadastramento,




    -- review this fields
    safe_cast(TRIM(informarbb) AS STRING) AS informarbb,
    safe_cast(TRIM(tipopag) AS STRING) AS tipopag,
    safe_cast(TRIM(foto) AS STRING) AS foto,
    safe_cast(TRIM(pontpubl) AS STRING) AS pontpubl,
    safe_cast(TRIM(flag_web) AS STRING) AS flag_web,
    safe_cast(TRIM(tipodoc_cert_fim) AS STRING) AS tipodoc_cert_fim,
    safe_cast(TRIM(dt_cert_fim) AS STRING) AS dt_cert_fim,
    safe_cast(TRIM(num_cert_fim) AS STRING) AS num_cert_fim,
    safe_cast(TRIM(livro_cert_fim) AS STRING) AS livro_cert_fim,
    safe_cast(TRIM(folha_cert_fim) AS STRING) AS folha_cert_fim,
    safe_cast(TRIM(cartorio_cert_fim) AS STRING) AS cartorio_cert_fim,
    safe_cast(TRIM(uf_cart_fim) AS STRING) AS uf_cart_fim,
    safe_cast(TRIM(municipio_cart_fim) AS STRING) AS municipio_cart_fim,
    safe_cast(TRIM(gera_pasep) AS STRING) AS gera_pasep,
    safe_cast(TRIM(matricula_cert_fim) AS STRING) AS matricula_cert_fim,
    safe_cast(TRIM(municipio_cart_fim_cod) AS STRING) AS municipio_cart_fim_cod,
    safe_cast(TRIM(pontarqs) AS STRING) AS pontarqs,






    SAFE_CAST(TRIM(flex_campo_01) AS STRING) AS flex_campo_01,
    SAFE_CAST(TRIM(flex_campo_04) AS STRING) AS flex_campo_04,
    SAFE_CAST(TRIM(flex_campo_05) AS STRING) AS flex_campo_05,
    SAFE_CAST(TRIM(flex_campo_29) AS STRING) AS flex_campo_29,
    SAFE_CAST(TRIM(flex_campo_31) AS STRING) AS flex_campo_31,
    SAFE_CAST(TRIM(flex_campo_32) AS STRING) AS flex_campo_32,
    SAFE_CAST(TRIM(flex_campo_33) AS STRING) AS flex_campo_33,
    SAFE_CAST(TRIM(flex_campo_34) AS STRING) AS flex_campo_34,
    SAFE_CAST(TRIM(flex_campo_35) AS STRING) AS flex_campo_35,
    SAFE_CAST(TRIM(flex_campo_37) AS STRING) AS flex_campo_37,
    SAFE_CAST(TRIM(flex_campo_38) AS STRING) AS flex_campo_38,
    SAFE_CAST(TRIM(flex_campo_39) AS STRING) AS flex_campo_39,
    SAFE_CAST(TRIM(flex_campo_41) AS STRING) AS flex_campo_41,
    SAFE_CAST(TRIM(flex_campo_42) AS STRING) AS flex_campo_42,
    SAFE_CAST(TRIM(flex_campo_43) AS STRING) AS flex_campo_43,
    SAFE_CAST(TRIM(flex_campo_44) AS STRING) AS flex_campo_44,
    SAFE_CAST(TRIM(flex_campo_45) AS STRING) AS flex_campo_45,
    SAFE_CAST(TRIM(flex_campo_46) AS STRING) AS flex_campo_46,
    SAFE_CAST(TRIM(flex_campo_47) AS STRING) AS flex_campo_47,
    SAFE_CAST(TRIM(flex_campo_48) AS STRING) AS flex_campo_48,
    SAFE_CAST(TRIM(flex_campo_49) AS STRING) AS flex_campo_49,
    SAFE_CAST(TRIM(flex_campo_50) AS STRING) AS flex_campo_50,
    SAFE_CAST(TRIM(flex_campo_57) AS STRING) AS flex_campo_57,
    SAFE_CAST(TRIM(flex_campo_61) AS STRING) AS flex_campo_61,
    SAFE_CAST(TRIM(flex_campo_62) AS STRING) AS flex_campo_62,
    SAFE_CAST(TRIM(flex_campo_63) AS STRING) AS flex_campo_63,
    SAFE_CAST(TRIM(flex_campo_64) AS STRING) AS flex_campo_64,
    SAFE_CAST(TRIM(flex_campo_65) AS STRING) AS flex_campo_65,
    SAFE_CAST(TRIM(flex_campo_66) AS STRING) AS flex_campo_66,
    SAFE_CAST(TRIM(flex_campo_67) AS STRING) AS flex_campo_67,
    SAFE_CAST(TRIM(flex_campo_68) AS STRING) AS flex_campo_68,
    SAFE_CAST(TRIM(flex_campo_71) AS STRING) AS flex_campo_71,
    SAFE_CAST(TRIM(flex_campo_72) AS STRING) AS flex_campo_72,
    SAFE_CAST(TRIM(flex_campo_73) AS STRING) AS flex_campo_73,
    SAFE_CAST(TRIM(flex_campo_74) AS STRING) AS flex_campo_74,
    SAFE_CAST(TRIM(flex_campo_75) AS STRING) AS flex_campo_75,
    SAFE_CAST(TRIM(flex_campo_76) AS STRING) AS flex_campo_76,
    SAFE_CAST(TRIM(flex_campo_77) AS STRING) AS flex_campo_77,
    SAFE_CAST(TRIM(flex_campo_78) AS STRING) AS flex_campo_78,
    SAFE_CAST(TRIM(flex_campo_79) AS STRING) AS flex_campo_79,
    SAFE_CAST(TRIM(flex_campo_81) AS STRING) AS flex_campo_81,
    SAFE_CAST(TRIM(flex_campo_82) AS STRING) AS flex_campo_82,
    SAFE_CAST(TRIM(flex_campo_83) AS STRING) AS flex_campo_83,
    SAFE_CAST(TRIM(flex_campo_84) AS STRING) AS flex_campo_84,
    SAFE_CAST(TRIM(flex_campo_85) AS STRING) AS flex_campo_85,
    SAFE_CAST(TRIM(flex_campo_86) AS STRING) AS flex_campo_86,
    SAFE_CAST(TRIM(flex_campo_87) AS STRING) AS flex_campo_87,
    SAFE_CAST(TRIM(flex_campo_88) AS STRING) AS flex_campo_88,
    SAFE_CAST(TRIM(flex_campo_91) AS STRING) AS flex_campo_91,
    SAFE_CAST(TRIM(flex_campo_92) AS STRING) AS flex_campo_92,
    SAFE_CAST(TRIM(flex_campo_93) AS STRING) AS flex_campo_93,
    SAFE_CAST(TRIM(flex_campo_94) AS STRING) AS flex_campo_94,
    SAFE_CAST(TRIM(flex_campo_95) AS STRING) AS flex_campo_95,
    SAFE_CAST(TRIM(flex_campo_96) AS STRING) AS flex_campo_96,
    SAFE_CAST(TRIM(flex_campo_97) AS STRING) AS flex_campo_97,
    SAFE_CAST(TRIM(flex_campo_98) AS STRING) AS flex_campo_98,
    SAFE_CAST(TRIM(flex_campo_99) AS STRING) AS flex_campo_99,
    SAFE_CAST(TRIM(flex_campo_100) AS STRING) AS flex_campo_100,





FROM {{ source('recursos_humanos_ergon_comlurb_staging', 'funcionario') }}