pull_request_rules:
  - name: Automatic update for PRs
    conditions:
      - -conflict
      - -draft
      - -closed
      - -merged
      - "#commits-behind>0"
      - label!=do-not-update
    actions:
      update:
  - name: Warn author on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}} esse pull request tem conflitos 😩"
      label:
        add:
          - conflict
