name: "queries"
version: "1.0.0"
config-version: 2

profile: "iplan"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


vars:
  # Internal variables
  DBT_USER: "{{ env_var('DBT_USER', 'dev_fantasma') }}"

models:
  +persist_docs:
    relation: true
    columns: true

  queries:
    mart:
      gerenciamento:
        custos:
          +tags: ["daily", "custos"]
      sme:
        frequencia:
          +materialized: table
          +schema: frequencia
          #+tags: ["daily", "sme"] REMOVE WHILE DB IS OFFLINE
          +project: rj-sme
    raw:
      +tags: "raw"
      bcadastro:
        +materialized: table
        +schema: brutos_bcadastro
        +tags: "weekly"
      gcp:
        +tags: ["daily", "custos"]
      taxirio:
        +materialized: table
        +schema: brutos_taxirio
        +tags: "daily"
      unidades_administrativas:
        +materialized: table
        +schema: brutos_unidades_administrativas
        +tags: "daily"
      sme:
        gestao_escolar:
          +materialized: table
          +schema: brutos_gestao_escolar
          #+tags: ["daily", "sme"] REMOVE WHILE DB IS OFFLINE
          +project: rj-sme
      smfp:
        +tags: "smfp"
        +project: rj-smfp
        recursos_humanos_ergon:
          +materialized: table
          +schema: brutos_recursos_humanos_ergon
          +tags: "daily"
      plus_codes:
        +materialized: table
        +schema: plus_codes
        +tags: "daily"
      eai_logs:
        +materialized: table
        +schema: eai_logs
      smi:
        +tags: "smi"
        +project: rj-smi
        infraestrutura_siscob_obras:
          +materialized: table
          +schema: infraestrutura_siscob_obras
          +tags: "daily"        
      smas:
        cadunico:
          +materialized: table
          +project: rj-smas
          +schema: brutos_data_metrica
      cvl:
        +tags: "cvl"
        +project: rj-cvl
        adm_contrato_gestao:
          +materialized: table
          +schema: adm_contrato_gestao
          +tags: "daily"
      segovi:
        +tags: "segovi"
        +project: rj-segovi
        adm_central_atendimento_1746:
          +materialized: table
          +schema: adm_central_atendimento_1746
      smtur:
        oferta_turistica:
          +materialized: view
          +schema: brutos_oferta_turistica
          +tags: "daily"
          +project: rj-iplanrio

        
