name: "queries"
version: "1.0.0"
config-version: 2

profile: "iplan"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


vars:
  # Internal variables
  DBT_USER: "{{ env_var('DBT_USER', 'dev_fantasma') }}"

  # Phone validation configuration
  phone_validation:
    # Limites de frequência para classificação de qualidade
    freq_valid_max: 5           # <= 5 pessoas = VÁLIDO
    freq_suspicious_min: 6      # 6-15 pessoas = SUSPEITO  
    freq_suspicious_max: 15
    freq_invalid_min: 16        # > 15 pessoas = INVÁLIDO
    
    # Padrões para detecção de números suspeitos
    max_repeated_digits: 5      # Máximo de dígitos repetidos seguidos
    suspicious_patterns:
      - "212121"               # Repetição de dois dígitos
      - "123123123"            # Repetição de três dígitos
    
    # Padrões conhecidos de números falsos/dummy
    dummy_patterns:
      - "123456789"            # Sequência numérica
      - "987654321"            # Sequência reversa
      - "111111111"            # Todos iguais
      - "000000000"            # Todos zeros
      - "999999999"            # Todos noves
      - "888888888"            # Todos oitos
    
    # Configuração por país
    countries:
      brasil:
        ddi: "55"
        celular_length: 9
        celular_prefix: "9"
        fixo_length: 8
        valid_ddds: [11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 24, 27, 28, 31, 32, 33, 34, 35, 37, 38, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51, 53, 54, 55, 61, 62, 63, 64, 65, 66, 67, 68, 69, 71, 73, 74, 75, 77, 79, 81, 82, 83, 84, 85, 86, 87, 88, 89, 91, 92, 93, 94, 95, 96, 97, 98, 99]
    
    # Configuração de auditoria
    rmi_version: "v1.1"
    hash_algorithm: "sha256"

models:
  +persist_docs:
    relation: true
    columns: true

  queries:
    udfs:
      +materialized: udf
      +schema: tools
    mart:
      gerenciamento:
        custos:
          +tags: ["daily", "custos"]
      sme:
        frequencia:
          +materialized: table
          +schema: frequencia
          #+tags: ["daily", "sme"] REMOVE WHILE DB IS OFFLINE
          +project: rj-sme
    intermediate:
      +materialized: ephemeral
      iplanrio:
        crm_registry:
          +tags: ["daily", "rmi"]
          crm_whatsapp:
            +tags: ["rmi", "whatsapp"]
          rmi_dados_mestres:
            +tags: "rmi"
          rmi_eventos:
            +tags: "rmi"
          rmi_conversas:
            +tags: ["rmi", "whatsapp"]
    core:
      +materialized: table
      +schema: dados_mestres
      facts:
        +materialized: table
        +partition_by:
          field: data_particao
          data_type: date
        iplanrio:
          crm_registry:
            +tags: ["daily", "rmi"]
            rmi_eventos:
              +tags: "rmi"
            rmi_conversas:
              +tags: ["rmi", "whatsapp"]
      dimensions:
        iplanrio:
          crm_registry:
            +tags: ["daily", "rmi"]
            crm_whatsapp:
              +tags: "whatsapp" # Add whatsapp tag to models under crm_whatsapp
            rmi_dados_mestres:
              +tags: "rmi"
      smfp:
        +project: rj-smfp
        ergon_saude:
          +materialized: table
          +schema: recursos_humanos_ergon_saude
          +tags: "daily"
      setur:
        +project: rj-setur
        observatorio_do_turismo:
          +materialized: table
          +schema: turismo_fluxo_visitantes
          +tags: "daily"
    raw:
      +tags: "raw"
      bcadastro:
        +materialized: table
        +schema: brutos_bcadastro
        +tags: "weekly"
      gcp:
        +tags: ["daily", "custos"]
      governo_integridade:
        +tags: ["daily", "segovi"]
      taxirio:
        +materialized: table
        +schema: brutos_taxirio
        +tags: "daily"
      unidades_administrativas:
        +materialized: table
        +schema: brutos_unidades_administrativas
        +tags: "daily"
      sme:
        gestao_escolar:
          +materialized: table
          +schema: brutos_gestao_escolar
          #+tags: ["daily", "sme"] REMOVE WHILE DB IS OFFLINE
          +project: rj-sme
      smfp:
        +tags: "smfp"
        +project: rj-smfp
        recursos_humanos_ergon:
          +materialized: table
          +schema: brutos_recursos_humanos_ergon
          +tags: "daily"
        sigma:
          +materialized: table
          +schema: compras_materiais_servicos_sigma
          +tags: "daily"
      sms:
        +tags: ["daily", "sms"]
      smtr:
        +tags: ["daily", "smtr"]
      plus_codes:
        +materialized: table
        +schema: plus_codes
        +tags: "daily"
      eai_logs:
        +materialized: table
        +schema: eai_logs
      smi:
        +tags: "smi"
        +project: rj-smi
        infraestrutura_siscob_obras:
          +materialized: table
          +schema: infraestrutura_siscob_obras
          +tags: "daily"        
      smas:
        +tags: ["daily", "smas"]
        cadunico:
          +materialized: table
          +project: rj-smas
          +schema: brutos_data_metrica
      cvl:
        +tags: "cvl"
        +project: rj-cvl
        adm_contrato_gestao:
          +materialized: table
          +schema: adm_contrato_gestao
          +tags: "daily"
      segovi:
        +tags: "segovi"
        +project: rj-segovi
        adm_central_atendimento_1746:
          +materialized: table
          +schema: adm_central_atendimento_1746
          +tags: "daily"
      setur:
        +project: rj-setur
        oferta_turistica:
          +materialized: view
          +schema: turismo_fluxo_visitantes_staging
          +tags: "daily"
        turismo_fluxo_visitantes:
          +materialized: table
          +schema: turismo_fluxo_visitantes_staging
          +tags: "daily"
      iplanrio:
        crm_registry:
          wetalkie:
            +tags: ["daily", "rmi", "whatsapp"]
        dados_mestres:
          +tags: "rmi"