name: "queries"
version: "1.0.0"
config-version: 2

profile: "iplan"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


vars:
  # Internal variables
  DBT_USER: "{{ env_var('DBT_USER', 'dev_fantasma') }}"
  HASH_SEED: "{{ env_var('HASH_SEED', 'hash_seed') }}"


models:
  +persist_docs:
    relation: true
    columns: true

  queries:
    mart:
      gerenciamento:
        custos:
          +tags: ["daily", "custos"]
          +resource_tags:
            rj-iplanrio/dominio: infraestrutura-ti
            845941190868/acesso": restrito
      sme:
        frequencia:
          +materialized: table
          +schema: educacao_basica_frequencia
          +tags: ["daily", "sme"]
          +project: rj-sme
      smfp:
        +project: rj-smfp
        ergon_saude:
          +materialized: table
          +schema: recursos_humanos_ergon_saude
          +tags: "daily"
      setur:
        +project: rj-setur
        observatorio_do_turismo:
          +materialized: table
          +schema: turismo_fluxo_visitantes
          +tags: "daily"
      iplanrio:
        +project: rj-iplanrio
        api_bcadastro:
          +schema: api_bcadastro
          +tags: ["daily", "bcadastro"]
          +resource_tags:
            rj-iplanrio/dominio: bcadastro
            845941190868/acesso: restrito
    raw:
      +tags: "raw"
      bcadastro:
        +materialized: table
        +schema: brutos_bcadastro
        +tags: "weekly"
        +resource_tags:
          rj-iplanrio/dominio: bcadastro
          845941190868/acesso": restrito
      gcp:
        +tags: ["daily", "custos"]
        +resource_tags:
          rj-iplanrio/dominio: infraestrutura-ti
          845941190868/acesso": restrito
      taxirio:
        +materialized: table
        +schema: brutos_taxirio
        +tags: "daily"
        +resource_tags:
          rj-iplanrio/dominio: taxirio
          845941190868/acesso": restrito
      unidades_administrativas:
        +materialized: table
        +schema: brutos_unidades_administrativas
        +tags: "daily"
        +resource_tags:
          rj-iplanrio/dominio: administrativo
          845941190868/acesso": interno
      sisbicho:
        +project: rj-iplanrio
        +materialized: table
        +schema: brutos_sisbicho
        +tags: "daily"
        +resource_tags:
          rj-iplanrio/dominio: sisbicho
          845941190868/acesso": restrito
      sme:
        +project: rj-sme
        +tags: ["sme"]
        gestao_escolar:
          +materialized: table
          +schema: brutos_gestao_escolar
          +tags: ["daily"]
        educacao_basica:
          +materialized: table
          +schema: educacao_basica_staging
          +tags: "daily"
      smfp:
        +tags: "smfp"
        +project: rj-smfp
        recursos_humanos_ergon:
          +materialized: table
          +schema: recursos_humanos_ergon
          +tags: "daily"
        sigma:
          +materialized: table
          +schema: compras_materiais_servicos_sigma
          +tags: "daily"
      plus_codes:
        +materialized: table
        +schema: plus_codes
        +tags: "daily"
        +resource_tags:
          rj-iplanrio/dominio: administrativo
          845941190868/acesso": interno
      eai_logs:
        +materialized: table
        +schema: eai_logs
        +resource_tags:
          rj-iplanrio/dominio: whatsapp
          845941190868/acesso": restrito
      smi:
        +tags: "smi"
        +project: rj-smi
        infraestrutura_siscob_obras:
          +materialized: table
          +schema: infraestrutura_siscob_obras
          +tags: "daily"
      smas:
        cadunico:
          +materialized: table
          +project: rj-smas
          +schema: brutos_data_metrica
      cvl:
        +tags: "cvl"
        +project: rj-cvl
        adm_contrato_gestao:
          +materialized: table
          +schema: adm_contrato_gestao
          +tags: "daily"
      segovi:
        +tags: "segovi"
        +project: rj-segovi
        adm_central_atendimento_1746:
          +materialized: table
          +schema: adm_central_atendimento_1746
          +tags: "daily"
      setur:
        +project: rj-setur
        oferta_turistica:
          +materialized: view
          +schema: turismo_fluxo_visitantes_staging
          +tags: "daily"
        turismo_fluxo_visitantes:
          +materialized: table
          +schema: turismo_fluxo_visitantes_staging
          +tags: "daily"
      mais_valia:
        +project: rj-iplanrio
        +materialized: table
        +schema: brutos_mais_valia
        +tags: ["daily", "mais_valia"]
        +resource_tags:
          rj-iplanrio/dominio: tributos
          845941190868/acesso": restrito
      pgm:
        +tags: "pgm"
        +project: rj-iplanrio
        divida_ativa:
          +materialized: table
          +schema: brutos_divida_ativa
          +tags: ["daily", "divida_ativa"]
          +resource_tags:
            rj-iplanrio/dominio: tributos
            845941190868/acesso": restrito
      
      iplanrio:
        +project: rj-iplanrio
        pessoa_vinculada:
          +materialized: table
          +schema: brutos_pessoa_vinculada
          +tags: ["daily", "pessoa_vinculada"]
          +resource_tags:
            rj-iplanrio/dominio: administrativo
            845941190868/acesso": restrito
        unidade_administrativa:
          +materialized: table
          +schema: brutos_sici
          +tags: ["daily", "unidade_administrativa"]
          +resource_tags:
            rj-iplanrio/dominio: administrativo
            845941190868/acesso": interno
flags:
  require_generic_test_arguments_property: true