name: "queries"
version: "1.0.0"
config-version: 2

profile: "iplan"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


vars:

  # BigQuery Monitoring
  bq_region: 'us'
  input_gcp_projects: ['rj-iplanrio']
  enable_gcp_bigquery_audit_logs: false
  gcp_billing_export_storage_project: 'rj-iplanrio'
  gcp_billing_export_dataset: 'gerenciamento_bigquery_billing'
  gcp_billing_export_table: 'gcp_billing_export'
  enable_gcp_billing_export: false
  gcp_bigquery_audit_logs_storage_project: 'rj-iplanrio'
  gcp_bigquery_audit_logs_dataset: 'gerenciamento_bigquery_audit_logs'
  gcp_bigquery_audit_logs_table: 'gcp_audit_logs'



models:
  +persist_docs:
    relation: true
    columns: true
  dbt_bigquery_monitoring:
    +schema: "gerenciamento_bigquery_monitoring"
  queries:
    raw:
      +tags: "raw"
      bcadastro:
        +materialized: table
        +schema: bcadastro
        +tags: "weekly"

