name: "queries"
version: "1.0.0"
config-version: 2

profile: "iplan"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


vars:
  # Internal variables
  DBT_USER: "{{ env_var('DBT_USER', 'dev_fantasma') }}"

  # BigQuery Monitoring
  bq_region: 'us'
  input_gcp_projects: ['rj-iplanrio']


  use_flat_pricing: false # We use on-demand pricing
  enable_gcp_bigquery_audit_logs: false # False until we have a solution to "labels" error
  gcp_bigquery_audit_logs_storage_project: 'rj-iplanrio'
  gcp_bigquery_audit_logs_dataset: 'logs_bq'
  gcp_bigquery_audit_logs_table: "{{ env_var('DBT_BQ_MONITORING_GCP_BIGQUERY_AUDIT_LOGS_TABLE') }}"
  should_combine_audit_logs_and_information_schema: true
  # https://cloud.google.com/billing/docs/how-to/export-data-bigquery-setup
  enable_gcp_billing_export: true
  gcp_billing_export_storage_project: 'dados-rio-billing'
  gcp_billing_export_dataset: "{{ env_var('DBT_BQ_MONITORING_GCP_BILLING_EXPORT_DATASET') }}"
  gcp_billing_export_table: "{{ env_var('DBT_BQ_MONITORING_GCP_BILLING_EXPORT_TABLE') }}"

  google_information_schema_model_materialization: 'ephemeral'


models:
  +persist_docs:
    relation: true
    columns: true
  dbt_bigquery_monitoring:
    +schema: "gerenciamento_bigquery_monitoring"

  queries:
    raw:
      +tags: "raw"
      bcadastro:
        +materialized: table
        +schema: brutos_bcadastro
        +tags: "weekly"
      unidades_administrativas:
        +materialized: table
        +schema: brutos_unidades_administrativas
        +tags: "daily"

