name: "queries"
version: "1.0.0"
config-version: 2

profile: "iplan"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  +persist_docs:
    relation: true
    columns: true
  queries:
    adm_processo_interno_processorio:
      +materialized: table
      +schema: adm_processo_interno_processorio
    adm_processo_interno_sicop:
      +materialized: table
      +schema: adm_processo_interno_sicop
    unidades_administrativas:
      +materialized: table
      +schema: unidades_administrativas
    transporte_rodoviario_taxirio:
      +materialized: table
      +schema: transporte_rodoviario_taxirio
    transporte_rodoviario_taxirio_homologacao:
      +materialized: table
      +schema: transporte_rodoviario_taxirio_homologacao
    dbt_bigquery_monitoring:
        +schema: "dbt_bigquery_monitoring"

vars:
  # dbt bigquery monitoring vars
  input_gcp_projects: [ 'rj-iplanrio','rj-iplanrio-dev']
