name: "queries"
version: "1.0.0"
config-version: 2

profile: "iplan"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  +persist_docs:
    relation: true
    columns: true
  queries:
    raw:
      +tags: "raw"
      bcadastro:
        +materialized: table
        +schema: bcadastro
        +tags: "daily"




# BigQuery Monitoring
vars:

  bq_region: 'us'
  input_gcp_projects: ['rj-iplanrio']
  enable_gcp_bigquery_audit_logs: false
  gcp_bigquery_audit_logs_storage_project: 'rj-iplanrio'
  gcp_bigquery_audit_logs_dataset: 'gerenciamento__bq_custos'
  gcp_bigquery_audit_logs_table: 'gerenciamento__bq_audit_logs'

query-comment:
  comment: '{{ dbt_bigquery_monitoring.get_query_comment(node) }}'
  job-label: True # Use query comment JSON as job labels