iplan:
  target: dev
  outputs:
    dev:
      schema: dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/geraldo/Projetos/DBT/Credencial/rj-iplanrio-af7a2b8f5bab.json
      location: US
      method: service-account
      priority: interactive
      project: rj-iplanrio-dev
      threads: 8
      type: bigquery
      
    prod:
      schema: dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/geraldo/Projetos/DBT/Credencial/rj-iplanrio-af7a2b8f5bab.json
      location: US
      method: service-account
      priority: interactive
      project: rj-iplanrio
      threads: 8
      type: bigquery
      

