version: 2
models:
  - name: processo
    description:
      "**Descrição**: Processo administrativo aberto na prefeitura do Rio\
      \ de Janeiro, tanto na administração direta como indireta. Um processo é um\
      \ conjunto de documentos que ganha um número na prefeitura do Rio. Um processo\
      \ pode ser de ofício ou de requerimento. Em um processo de requerimento um cidadão\
      \ faz um pedido à prefeitura do Rio. O de ofício inicia um conjunto de passos\
      \ pré-determinados para alcançar determinado objeto.\n**Frequência de atualização**:\
      \ Diário\n**Cobertura temporal**: Desde 1991.\n**Órgão gestor dos dados**: SMA\n\
      **Publicado por**: Denise Malagoli Vaz\n**Publicado por (email)**: denise.vaz@sma.rio.rj.gov.br\n"
    columns:
      - name: org_transc
        description: Órgão que cadastrou o processo no sistema.
      - name: num_processo
        description:
          Número dado pela prefeitura ao processo. No número constam a
          secretaria e o ano de abertura.
      - name: cpf_cgc
        description:
          Número do documento do requerente de acordo com o atributo ident.
          Quando é por ofício fica em branco.
      - name: ident
        description:
          "Tipo do documento fornecido pelo requerente. 1-CPF, 2-CNPJ,\
          \ 3-Inscrição Imobiliária, 4-Inscrição Municipal, 5-matrícula, 6-Número\
          \ do CASS, 7-Notificação, \r\n8-Número Cadastral do Imóvel, 9-Identidade,\
          \ 10-Órgão da Administração Pública/Requerente sem documento, \r\n11–Notificação\
          \ (Multa de Transporte Urbano). Quando é por ofício fica em branco."
      - name: requerente
        description:
          Nome do requerente do processo. Requerente é a pessoa que solicita
          a abertura do processo.
      - name: cod_assu_p
        description:
          Código do assunto ao qual o processo é relativo. Um processo
          sempre é relativo a um assunto pré-determinado.
      - name: desc_assun
        description: Descrição do assunto relativo ao atributo cod_assu_p.
      - name: mat_transc
        description: Matrícula do servidor que incluiu o processo no sistema.
      - name: status
        description:
          Tipo do processo. Ex. –1 (PROCESSO APENSO) --2 (PROCESSO DESAPENSO)
          --3 (PROCESSO ANEXADO) --4 (PROCESSO DESANEXADO) --5 (PROCESSO JUNTADO)
          --6 (DESJUNTADO) --7 (PROCESSO PRINCIPAL) --8 (PROCESSO PRINCIPAL APENSO)
      - name: ano_proc2
        description: Ano da data em que foi aberto o protocolo para o processo.
      - name: dia_proc2
        description: Dia da data em que foi aberto o protocolo para o  processo.
      - name: mes_proc2
        description: Mês da data em que foi aberto o protocolo para o processo.
      - name: sec_proc2
        description:
          Século da data em que foi aberto o protocolo para o processo,
          podendo ser 20 ou 21.
      - name: ano_sist2
        description: Ano da data em que o processo foi inserido no sistema.
      - name: sec_sist2
        description:
          Século da data em que o processo foi inserido no sistema, podendo
          ser 20 ou 21.
      - name: mes_sist2
        description: Mês da data em que o processo foi inserido no sistema.
      - name: dia_sist2
        description: Dia da data em que o processo foi inserido no sistema.
  - name: orgao
    description:
      "**Descrição**: Órgão da prefeitura do Rio de Janeiro. Um órgão pode\
      \ ser uma secretaria, uma empresa da prefeitura, própria prefeitura, a vice-prefeitura\
      \ ou a procuradoria geral do município.\n**Frequência de atualização**: Diário\n\
      **Cobertura temporal**: Desde 1991.\n**Órgão gestor dos dados**: SMA\n**Publicado\
      \ por**: Denise Malagoli Vaz\n**Publicado por (email)**: denise.vaz@sma.rio.rj.gov.br\n"
    columns:
      - name: chave
        description: Identificador único usado no banco de dados para o órgão.
      - name: org_sicop
        description: código do órgão no SICOP.
      - name: cod_orcto
        description: código do órgão no Orçamento.
  - name: documento
    description:
      "**Descrição**: Documento que faz parte de um processo administrativo\
      \ da prefeitura do Rio de Janeiro.\n**Frequência de atualização**: Diário\n\
      **Cobertura temporal**: Desde 1991.\n**Órgão gestor dos dados**: SMA\n**Publicado\
      \ por**: Denise Malagoli Vaz\n**Publicado por (email)**: denise.vaz@sma.rio.rj.gov.br\n"
    columns:
      - name: chave
        description:
          Identificador único desta inclusão de documento. É formado pela
          concatenação de org_resp+tipo_doc+Número do documento
      - name: org_resp
        description: Órgão que recebeu o documento.
      - name: org_transc
        description: Órgão que cadastrou o documento no sistema.
      - name: tipo_doc
        description: Tipo do documento. Ex. Memorando, carta,ofício etc.
      - name: num_documento
        description: Número único dado pela prefeitura do Rio de Janeiro ao documento
      - name: requerente
        description: Pessoa que entrega o documento na prefeitura do Rio de Janeiro.
      - name: cod_assun
        description:
          Código do assunto. Chave que indica qual o assunto relacionado
          ao documento.
      - name: mat_transc
        description: Matrícula do servidor que incluiu o documento no sistema.
      - name: assun_comp
        description:
          Descrição complementar ao assunto relativo ao documento. É um
          texto livre.
      - name: sec_sist2
        description:
          Século da data em que foi aberto o protocolo para o documento,
          podendo ser 20 ou 21.
      - name: ano_sist2
        description: Ano da data em que foi aberto o protocolo para o documento.
      - name: mes_sist2
        description: Mês da data em que foi aberto o protocolo para o documento.
      - name: dia_sist2
        description: Dia da data em que foi aberto o protocolo para o documento.
  - name: assunto
    description:
      "**Descrição**: Assunto que pode ser associado a um processo administrativo\
      \ ou a um documento incluído em um processo administrativo da prefeitura do\
      \ Rio de Janeiro.\n**Frequência de atualização**: Diário\n**Cobertura temporal**:\
      \ Desde 1991.\n**Órgão gestor dos dados**: SMA\n**Publicado por**: Denise Malagoli\
      \ Vaz\n**Publicado por (email)**: denise.vaz@sma.rio.rj.gov.br\n"
    columns:
      - name: ident
        description:
          "Indica o tipo de registro na visão. 1: tabela de assuntos, 2:
          tabela de despachos e 6: tipo de documento. As relativas a assunto são somente
          do tipo 1."
      - name: cod
        description:
          Código do assunto, despacho ou documento. Identificador único
          dado pela prefeitura do Rio de Janeiro.
      - name: seq
        description:
          Indica a sequência da descrição do assunto, despacho ou documento.
          Somente a última sequência tem o valor atual do assunto, as sequências anteriores
          são guardadas como histórico.
      - name: desc_assunto
        description: Descrição do assunto, despacho ou documento.
  - name: tramitacao_documento
    description:
      "**Descrição**: Tramitação de um documento na prefeitura do Rio de\
      \ Janeiro. Uma tramitação ocorre quando um órgão envia para outro órgão da prefeitura\
      \ do Rio de Janeiro para ser executada uma ação em relação ao documento.\n**Frequência\
      \ de atualização**: Diário\n**Cobertura temporal**: Desde 1991.\n**Órgão gestor\
      \ dos dados**: SMA\n**Publicado por**: Denise Malagoli Vaz\n**Publicado por\
      \ (email)**: denise.vaz@sma.rio.rj.gov.br\n"
    columns:
      - name: org_resp
        description: Código do órgão onde o requerente entregou o documento.
      - name: num_documento
        description: Número dado pela prefeitura do Rio de Janeiro ao documento.
      - name: seq
        description:
          Número da tramitação. A primeira tramitação do documento ganha
          o número 1.
      - name: destino
        description: Código do órgão para onde foi envidado o documento na tramitação.
      - name: cod_desp
        description:
          Código do despacho a ser feito no órgão destino. Despacho é a
          ação que o documento sofre. Ex. Mandar arquivos, tomar ciência, assinar,
          providenciar pagamento.
      - name: sec_remes2
        description:
          Século da data da última tramitação do documento, podendo ser
          20 ou 21.
      - name: ano_remes2
        description: Ano da data da última tramitação do documento.
      - name: mes_remes2
        description: Mês da data da última tramitação do documento.
      - name: dia_remes2
        description: Dia da data da última tramitação do documento.
  - name: apenso
    description:
      "**Descrição**: Processo administrativo da prefeitura do Rio de Janeiro\
      \ que foi apensado a um outro processo administrativo da prefeitura do Rio de\
      \ Janeiro.\n**Frequência de atualização**: Diário\n**Cobertura temporal**: Desde\
      \ 1991.\n**Órgão gestor dos dados**: SMA\n**Publicado por**: Denise Malagoli\
      \ Vaz\n**Publicado por (email)**: denise.vaz@sma.rio.rj.gov.br\n"
    columns:
      - name: chave
        description:
          Identificador único dado pela prefeitura do Rio de Janeiro ao
          apensamento.
      - name: num_processo_principal
        description: Número do processo administrativo ao qual o processo foi apensado.
      - name: num_processo
        description: Número do processo que foi apensado
      - name: i22005_cod_oper
        description:
          "Código da operação, que pode ter os valores: –1 (PROCESSO APENSO)
          --2 (PROCESSO DESAPENSO) --3 (PROCESSO ANEXADO) --4 (PROCESSO DESANEXADO)
          --5 (PROCESSO JUNTADO) --6 (DESJUNTADO) --7 (PROCESSO PRINCIPAL) --8 (PROCESSO
          PRINCIPAL APENSO)"
