{{
    config(     
        schema="brutos_consulta_previa_eventos",
        alias="alvaras_consulta_previa_eventos",
        materialized="table",
        tags=["raw", "alvaras", "eventos"],
        description="Alvarás de Eventos e Consultas Prévias.",
        partition_by={
            "field": "data_inicio_processo_cpe",
            "data_type": "timestamp",
            "granularity": "day"
        },
    )
}}

SELECT safe_cast(id_cpe as int64) as codigo_consulta_previa_evento,
       safe_cast(numero_cpe as string) as numero_consulta_previa_evento,
       safe_cast(nome_requerente as string) as nome_requerente,
       safe_cast(telefone_requerente as string) as telefone_requerente,
       safe_cast(inscricao_municipal as string) as inscricao_municipal,
       safe_cast(cpf as string) as cpf,
       safe_cast(cnpj as string) as cnpj,
       safe_cast(rg as string) as rg,
       safe_cast(email as string) as email,
       safe_cast(cidade_requerente as string) as cidade_requerente,
       safe_cast(logradouro_requerente as string) as logradouro_requerente,
       safe_cast(porta_requerente as int64) as porta_requerente,
       safe_cast(nome_evento as string) as nome_evento,
       safe_cast(ap as string) as ap,
       safe_cast(local_evento as string) as local_evento,
       safe_cast(area_publica as boolean) as area_publica,
       safe_cast(area_privada as boolean) as area_privada,
       safe_cast(area_ocupada_m2 as int64) as area_ocupada_m2,
       safe_cast(montagem_praia as boolean) as montagem_praia,
       safe_cast(fechamento_rua as boolean) as fechamento_rua,
       safe_cast(descricao_alteracao as string) as descricao_alteracao,
       safe_cast(estimativa_publico as int64) as estimativa_publico,
       safe_cast(publicidade as boolean) as publicidade,
       safe_cast(fogos_artificio as boolean) as fogos_artificio,
       safe_cast(empresa_seguranca as boolean) as empresa_seguranca,
       safe_cast(aberto_publico as boolean) as aberto_publico,
       safe_cast(cobranca_ingresso as boolean) as cobranca_ingresso,
       safe_cast(estrutura as boolean) as estrutura,
       safe_cast(manipulacao_alimentos as boolean) as manipulacao_alimentos,
       safe_cast(filmagem as boolean) as filmagem,
       safe_cast(reserva_vagas as boolean) as reserva_vagas,
       safe_cast(tipo_estrutura as string) as tipo_estrutura,
       safe_cast(descricao_evento as string) as descricao_evento,
       safe_cast(data_evento_inicio as datetime) as data_evento_inicio,
       safe_cast(data_evento_fim as datetime) as data_evento_fim,
       safe_cast(data_abertura_cpe as datetime) as data_abertura_cpe,
       safe_cast(aprovador as string) as aprovador,
       safe_cast(decisao_aprovador as string) as decisao_aprovador,
       safe_cast(codigo_decisao_aprovador as int64) as codigo_decisao_aprovador,
       safe_cast(observacao_aprovador as string) as observacao_aprovador,
       safe_cast(orgaos as string) as orgaos,
       safe_cast(competencia as string) as competencia,
       safe_cast(porta_evento as int64) as porta_evento,
       safe_cast(logradouro_evento as string) as logradouro_evento,
       safe_cast(estimativa_publica as int64) as estimativa_publica,
       safe_cast(declaracaoReferenteAVinculoDeRepresentacao as boolean) as declaracaoReferenteAVinculoDeRepresentacao,
       safe_cast(certAprovBombeiro as boolean) as certAprovBombeiro,
       safe_cast(plantaArea as boolean) as plantaArea,
       safe_cast(declaEntreDocVerdadeiro as boolean) as declaEntreDocVerdadeiro,
       safe_cast(decContratServLimpeza as boolean) as decContratServLimpeza,
       safe_cast(decInstBanheirosQuimicos as boolean) as decInstBanheirosQuimicos,
       safe_cast(declaracaoNormasEstaduaisSeguran as boolean) as declaracaoNormasEstaduaisSeguran,
       safe_cast(contratoSeguranca as boolean) as contratoSeguranca,
       safe_cast(declaResponsAmbiental as boolean) as declaResponsAmbiental,
       safe_cast(decRealizEventoSMF as boolean) as decRealizEventoSMF,
       safe_cast(aprovSecSMTR as boolean) as aprovSecSMTR,
       safe_cast(declaracaoReferenteAsNormasDeSeguranca as boolean) as declaracaoReferenteAsNormasDeSeguranca,
       safe_cast(IPHAN as boolean) as IPHAN,
       safe_cast(nadaOporSub as boolean) as nadaOporSub,
       safe_cast(vigilanciaSanitaria as boolean) as vigilanciaSanitaria,
       safe_cast(nenhumDocNece as boolean) as nenhumDocNece,
       safe_cast(outros as boolean) as outros,
       safe_cast(numero_processo_alvara as string) as numero_processo_alvara,
       safe_cast(data_inicio_processo_alvara as datetime) as data_inicio_processo_alvara,
       safe_cast(data_fim_processo_alvara as datetime) as data_fim_processo_alvara,
       safe_cast(data_inicio_processo_cpe as datetime) as data_inicio_processo_cpe,
       safe_cast(data_fim_processo_cpe as datetime) as data_fim_processo_cpe,
       safe_cast(Incide_TLE_cpe as boolean) as Incide_TLE_cpe,
       safe_cast(Incide_TUAP_cpe as boolean) as Incide_TUAP_cpe,
       safe_cast(Incide_TLE_alvara as boolean) as Incide_TLE_alvara,
       safe_cast(Incide_TUAP_alvara as boolean) as Incide_TUAP_alvara,
       safe_cast(codigo_TLE_cpe as string) as codigo_TLE_cpe,
       safe_cast(titulo_TLE_cpe as string) as titulo_TLE_cpe,
       safe_cast(codigo_receita_TLE_cpe as string) as codigo_receita_TLE_cpe,
       safe_cast(data_emissao_TLE_cpe as datetime) as data_emissao_TLE_cpe,
       safe_cast(taxa_liberada_TLE_cpe as boolean) as taxa_liberada_TLE_cpe,
       safe_cast(valor_TLE_cpe as int64) as valor_TLE_cpe,
       safe_cast(competencia_TLE_cpe as string) as competencia_TLE_cpe,
       safe_cast(numero_darm_TLE_cpe as string) as numero_darm_TLE_cpe,
       safe_cast(inscricao_municipal_TLE_cpe as string) as inscricao_municipal_TLE_cpe,
       safe_cast(data_pagamento_TLE_cpe as date) as data_pagamento_TLE_cpe,
       safe_cast(data_vencimento_TLE_cpe as date) as data_vencimento_TLE_cpe,
       safe_cast(status_TLE_cpe as string) as status_TLE_cpe,
       safe_cast(codigo_TUAP_cpe as string) as codigo_TUAP_cpe,
       safe_cast(titulo_TUAP_cpe as string) as titulo_TUAP_cpe,
       safe_cast(codigo_receita_TUAP_cpe as string) as codigo_receita_TUAP_cpe,
       safe_cast(data_emissao_TUAP_cpe as date) as data_emissao_TUAP_cpe,
       safe_cast(taxa_liberada_TUAP_cpe as boolean) as taxa_liberada_TUAP_cpe,
       safe_cast(valor_TUAP_cpe as int64) as valor_TUAP_cpe,
       safe_cast(competencia_TUAP_cpe as string) as competencia_TUAP_cpe,
       safe_cast(numero_darm_TUAP_cpe as string) as numero_darm_TUAP_cpe,
       safe_cast(inscricao_municipal_TUAP_cpe as string) as inscricao_municipal_TUAP_cpe,
       safe_cast(data_pagamento_TUAP_cpe as date) as data_pagamento_TUAP_cpe,
       safe_cast(data_vencimento_TUAP_cpe as date) as data_vencimento_TUAP_cpe,
       safe_cast(status_TUAP_cpe as string) as status_TUAP_cpe,
       safe_cast(codigo_TLE_alvara as string) as codigo_TLE_alvara,
       safe_cast(titulo_TLE_alvara as string) as titulo_TLE_alvara,
       safe_cast(codigo_receita_TLE_alvara as string) as codigo_receita_TLE_alvara,
       safe_cast(data_emissao_TLE_alvara as date) as data_emissao_TLE_alvara,
       safe_cast(taxa_liberada_TLE_alvara as boolean) as taxa_liberada_TLE_alvara,
       safe_cast(valor_TLE_alvara as int64) as valor_TLE_alvara,
       safe_cast(competencia_TLE_alvara as string) as competencia_TLE_alvara,
       safe_cast(numero_darm_TLE_alvara as string) as numero_darm_TLE_alvara,
       safe_cast(inscricao_municipal_TLE_alvara as string) as inscricao_municipal_TLE_alvara,
       safe_cast(data_pagamento_TLE_alvara as date) as data_pagamento_TLE_alvara,
       safe_cast(data_vencimento_TLE_alvara as date) as data_vencimento_TLE_alvara,
       safe_cast(status_TLE_alvara as string) as status_TLE_alvara,
       safe_cast(codigo_TUAP_alvara as string) as codigo_TUAP_alvara,
       safe_cast(titulo_TUAP_alvara as string) as titulo_TUAP_alvara,
       safe_cast(codigo_receita_TUAP_alvara as string) as codigo_receita_TUAP_alvara,
       safe_cast(data_emissao_TUAP_alvara as date) as data_emissao_TUAP_alvara,
       safe_cast(taxa_liberada_TUAP_alvara as boolean) as taxa_liberada_TUAP_alvara,
       safe_cast(valor_TUAP_alvara as int64) as valor_TUAP_alvara,
       safe_cast(competencia_TUAP_alvara as string) as competencia_TUAP_alvara,
       safe_cast(numero_darm_TUAP_alvara as string) as numero_darm_TUAP_alvara,
       safe_cast(inscricao_municipal_TUAP_alvara as string) as inscricao_municipal_TUAP_alvara,
       safe_cast(data_pagamento_TUAP_alvara as date) as data_pagamento_TUAP_alvara,
       safe_cast(data_vencimento_TUAP_alvara as date) as data_vencimento_TUAP_alvara,
       safe_cast(status_TUAP_alvara as string) as status_TUAP_alvara,
       _airbyte_extracted_at as loaded_at, 
       current_timestamp() as transformed_at
  FROM
     {{ source('brutos_consulta_previa_eventos_staging','vw_Consulta_Previa_Eventos') }}     