{{
    config(
        alias='funcionario',
        materialized="table",
        tags=["raw", "ergon", "funcionario"],
        description="Tabela que contém os registros dos funcionários da administração direta ou indireta da prefeitura do Rio de Janeiro."
    )
}}

SELECT
    {{ clean_and_cast('NUMERO', 'int64') }} AS id_funcionario,
    SAFE_CAST(NOME AS STRING) AS nome_funcionario,
    SAFE_CAST(FLEX_CAMPO_03 AS STRING) AS nome_social,
    SAFE_CAST(TRATAMENTO AS STRING) AS nome_tratamento,
    SAFE_CAST(SEXO AS STRING) AS sexo,
    SAFE_CAST(CAST(RACA AS STRING) AS STRING) AS codigo_raca_cor,
    SAFE_CAST(DEFICIENTE AS STRING) AS deficiente,
    SAFE_CAST(TIPODEFIC AS int64) AS codigo_deficiencia,
    safe_cast(SAFE_CAST(DTNASC as timestamp) AS DATE) AS data_nascimento,
    SAFE_CAST(FLEX_CAMPO_69 AS STRING) AS pais_nascimento,
    SAFE_CAST(CIDNASC AS STRING) AS nome_municipio_nascimento,
    SAFE_CAST(CIDADEENDER_COD AS STRING) AS municipio_moradia,
    SAFE_CAST(UFNASC AS STRING) AS sigla_uf_nascimento,
    SAFE_CAST(G_SANGUINEO AS STRING) AS grupo_sanguineo,
    SAFE_CAST(PAI AS STRING) AS nome_pai,
    SAFE_CAST(MAE AS STRING) AS nome_mae,
    SAFE_CAST(ESTCIVIL AS STRING) AS estado_civil,
    {{ clean_and_cast('ESCOLARIDADE', 'string') }} AS escolaridade,
    {{ clean_and_cast('NACIONALIDADE', 'string') }} AS nacionalidade,
    SAFE_CAST(TIPOLOGENDER AS STRING) AS tipo_logradouro,
    SAFE_CAST(NOMELOGENDER AS STRING) AS logradouro,
    SAFE_CAST(CAST(NUMENDER AS STRING) AS STRING) AS numero_porta,
    SAFE_CAST(COMPLENDER AS STRING) AS complemento_numero_porta,
    SAFE_CAST(BAIRROENDER AS STRING) AS bairro,
    SAFE_CAST(CIDADEENDER AS STRING) AS municipio,
    SAFE_CAST(UFENDER AS STRING) AS sigla_uf,
    SAFE_CAST(CAST(CEPENDER AS STRING) AS STRING) AS cep,
    SAFE_CAST(FLEX_CAMPO_89 AS STRING) AS cep_exterior,
    SAFE_CAST(NUMTEL_CELULAR AS STRING) AS celular,
    SAFE_CAST(TELEFONE AS STRING) AS telefone,
    SAFE_CAST(RAMAL AS STRING) AS ramal,
    SAFE_CAST(E_MAIL AS STRING) AS email,
    SAFE_CAST(FLEX_CAMPO_90 AS STRING) AS email_alternativo,
    SAFE_CAST(CAST(ANOPRIMEMP AS STRING) AS STRING) AS ano_primeiro_emprego,
    SAFE.PARSE_DATE('%d/%m/%Y', NULLIF(TRIM(FLEX_CAMPO_70), '')) AS data_primeiro_emprego, 
    SAFE_CAST(UFEMPANT AS STRING) AS sigla_uf_emprego_anterior,
    safe_cast(FLEX_CAMPO_80 as string) AS data_primeira_habitacao,
    SAFE_CAST(FLEX_CAMPO_51 AS STRING) AS deficiente_fisico,
    SAFE_CAST(FLEX_CAMPO_52 AS STRING) AS deficiente_visual,
    SAFE_CAST(FLEX_CAMPO_53 AS STRING) AS deficiente_auditivo,
    SAFE_CAST(FLEX_CAMPO_54 AS STRING) AS deficiente_mental,
    SAFE_CAST(FLEX_CAMPO_55 AS STRING) AS deficiente_intelectual,
    {{ clean_and_cast('NUMRG', 'string') }} AS id_rg,
    SAFE_CAST(TIPORG AS STRING) AS tipo_rg,
    SAFE_CAST(ORGAORG AS STRING) AS emissor_rg,
    SAFE_CAST(UFRG AS STRING) AS sigla_uf_rg,
    safe_cast(SAFE_CAST(EXPEDRG as timestamp) AS DATE)  AS data_expedicao_rg,
    {{ clean_and_cast('CPF', 'string') }} AS cpf,
    {{ clean_and_cast('NUMCARTPRO', 'string') }} AS ctps,
    SAFE_CAST(SERCARTPRO AS STRING) AS serie_ctps,
    SAFE_CAST(UFCARTPRO AS STRING) AS sigla_uf_ctps,
    {{ clean_and_cast('NUMTITEL', 'string') }} AS id_titulo_eleitor,
    SAFE_CAST(CAST(ZONATITEL AS STRING) AS STRING) AS zona_eleitoral,
    SAFE_CAST(CAST(SECTITEL AS STRING) AS STRING) AS secao_eleitoral,
    SAFE_CAST(UFTITEL AS STRING) AS sigla_uf_titulo_eleitor,
    {{ clean_and_cast('NUMDOCMILI', 'string') }} AS id_documento_militar,
    SAFE_CAST(SERDOCMILI AS STRING) AS serie_documento_militar,
    SAFE_CAST(CATMILI AS STRING) AS categoria_militar,
    SAFE_CAST(ORGAOMILI AS STRING) AS emissor_documento_militar,
    SAFE_CAST(UFDOCMILI AS STRING) AS sigla_uf_documento_militar,
    {{ clean_and_cast('CNH', 'string') }} AS cnh,
    SAFE_CAST(CATCNH AS STRING) AS categoria_cnh,
    safe_cast(SAFE_CAST(VALIDCNH AS timestamp) as date) AS validade_cnh,
    SAFE_CAST(UFCNH AS STRING) AS sigla_uf_cnh,
    SAFE_CAST(FLEX_CAMPO_26 AS STRING) AS orgao_emissor_cnh,
    SAFE.PARSE_DATE('%d/%m/%Y', NULLIF(TRIM(FLEX_CAMPO_27), '')) AS data_expedicao_cnh,
    {{ clean_and_cast('PISPASEP', 'string') }} AS id_pispasep,
    safe_cast(SAFE_CAST(DATAPIS AS timestamp) as date) AS data_inicio_pis,
    {{ clean_and_cast('FLEX_CAMPO_40', 'string') }} AS nis,
    SAFE_CAST(CAST(BANCOPIS AS STRING) AS STRING) AS numero_banco_nis,
    {{ clean_and_cast('IDENTPROF', 'string') }} AS identidade_profissional,
    {{ clean_and_cast('TIPOIDPROF', 'string') }} AS tipo_identidade_profissional,
    {{ clean_and_cast('FLEX_CAMPO_06', 'string') }} AS id_ric,
    SAFE_CAST(FLEX_CAMPO_07 AS STRING) AS emissor_ric,
    SAFE.PARSE_DATE('%d/%m/%Y', NULLIF(TRIM(FLEX_CAMPO_08), '')) AS data_emissao_ric,
    SAFE.PARSE_DATE('%d/%m/%Y', NULLIF(TRIM(FLEX_CAMPO_28), '')) AS expedicao_documento_orgao_classe,
    SAFE_CAST(FLEX_CAMPO_30 AS STRING) AS emissor_documento_orgao_classe,
    SAFE_CAST(UF_IDENTPROF AS STRING) AS sigla_uf_documento_orgao_classe,
    SAFE_CAST(FLEX_CAMPO_02 AS STRING) AS possui_impedimento,
    SAFE_CAST(CAST(BANCO AS STRING) AS STRING) AS numero_banco,
    SAFE_CAST(AGENCIA AS STRING) AS agencia_banco,
    SAFE_CAST(CONTA AS STRING) AS conta_banco,
    SAFE.PARSE_DATE('%d/%m/%Y', NULLIF(TRIM(FLEX_CAMPO_36), '')) AS data_ultima_atualizacao_bancaria,
    {{ clean_and_cast('TIPODOC_CERT', 'string') }} AS tipo_certidao,
    {{ clean_and_cast('NUM_CERT', 'string') }} AS livro_certidao,
    {{ clean_and_cast('FOLHA_CERT', 'string') }} AS folha_certidao,
    {{ clean_and_cast('CARTORIO_CERT', 'string') }} AS cartorio_ceridao,
    {{ clean_and_cast('UF_CART', 'string') }} AS sigla_uf_cartorio_certidao,
    {{ clean_and_cast('MUNICIPIO_CART_COD', 'string') }} AS municipio_emissor_certidao,
    SAFE_CAST(MUNICIPIO_CART AS STRING) AS municipio_cartorio_emissor_certudai,
    {{ clean_and_cast('MATRICULA_CERT', 'string') }} AS matricula_certidao,
    SAFE_CAST(FLEX_CAMPO_16 AS STRING) AS trabalho_voluntario,
    SAFE_CAST(FLEX_CAMPO_17 AS STRING) AS interesse_trabalho_voluntario,
    SAFE_CAST(FLEX_CAMPO_18 AS STRING) AS interesse_projeto_olimpico,
    SAFE_CAST(FLEX_CAMPO_19 AS STRING) AS interesse_projetos_sociais,
    {{ clean_and_cast('FLEX_CAMPO_56', 'string') }} AS recebe_beneficio_previdenciario,
    SAFE_CAST(FLEX_CAMPO_58 AS STRING) AS nome_posse_alteracao_sexo,
    SAFE_CAST(FLEX_CAMPO_59 AS STRING) AS sexo_posse_alteracao_sexo,
    SAFE.PARSE_DATE('%d/%m/%Y', NULLIF(TRIM(FLEX_CAMPO_60), ''))  AS data_alteracao_sexo,
    {{ clean_and_cast('FLEX_CAMPO_09', 'string') }} AS id_rne,
    SAFE_CAST(CAST(CHEGBRASIL AS STRING) AS STRING) AS ano_chegada_brasil,
    SAFE_CAST(FLEX_CAMPO_10 AS STRING) AS emissor_rne,
    SAFE.PARSE_DATE('%d/%m/%Y', NULLIF(TRIM(FLEX_CAMPO_11), ''))  AS data_expedicao_rne,
    SAFE.PARSE_DATE('%d/%m/%Y', NULLIF(TRIM(FLEX_CAMPO_12), ''))  AS data_chegada_estrangeiro,
    SAFE.PARSE_DATE('%d/%m/%Y', NULLIF(TRIM(FLEX_CAMPO_13), ''))  AS data_naturalizacao,
    SAFE_CAST(FLEX_CAMPO_14 AS STRING) AS estrangeiro_casado_brasileiro,
    SAFE_CAST(FLEX_CAMPO_15 AS STRING) AS estrangeiro_filho_brasileiro,
    SAFE_CAST(FLEX_CAMPO_20 AS STRING) AS login_facebook,
    SAFE_CAST(FLEX_CAMPO_21 AS STRING) AS login_twitter,
    SAFE_CAST(FLEX_CAMPO_22 AS STRING) AS login_google_plus,
    SAFE_CAST(FLEX_CAMPO_23 AS STRING) AS login_instagram,
    SAFE_CAST(FLEX_CAMPO_24 AS STRING) AS login_linkedin,
    SAFE_CAST(FLEX_CAMPO_25 AS STRING) AS login_myspace,
    SAFE_CAST(CAST(ID_REG AS STRING) AS STRING) AS ID_REG,
    _airbyte_extracted_at as updated_at
FROM {{ source('brutos_ergon_staging', 'VW_DLK_ERG_FUNCIONARIOS')}}