{{config(
    materialized = 'table',
    alias = 'brutos_consulta_previa_eventos',
    partition_by = {
        "field": "data_inicio_processo_cpe",
        "data_type": "date",
        "granularity": "day"
    }
)
}}

select
    safe_cast(id_cpe as int64) codigo_cpe,
    safe_cast(numero_cpe as string) numero_cpe,
    safe_cast(nome_requerente as string) nome_requerente,
    safe_cast(telefone_requerente as string) telefone_requerente,
    safe_cast(inscricao_municipal as string) inscricao_municipal,
    safe_cast(cpf as string) cpf,
    safe_cast(cnpj as string) cnpj,
    safe_cast(rg as string) rg,
    safe_cast(email as string) email,
    safe_cast(cidade_requerente as string) cidade_requerente,
    safe_cast(logradouro_requerente as string) logradouro_requerente,
    safe_cast(porta_requerente as int64) porta_requerente,
    safe_cast(nome_evento as string) nome_evento,
    safe_cast(ap as string) ap,
    safe_cast(local_evento as string) local_evento,
    safe_cast(area_publica as boolean) area_publica,
    safe_cast(area_privada as boolean) area_privada,
    safe_cast(area_ocupada_m2 as float64) area_ocupada_m2,
    safe_cast(montagem_praia as boolean) montagem_praia,
    safe_cast(fechamento_rua as boolean) fechamento_rua,
    safe_cast(descricao_alteracao as string) descricao_alteracao,
    safe_cast(estimativa_publico as int64) estimativa_publico,
    safe_cast(publicidade as boolean) publicidade,
    safe_cast(fogos_artificio as boolean) fogos_artificio,
    safe_cast(empresa_seguranca as boolean) empresa_seguranca,
    safe_cast(aberto_publico as boolean) aberto_publico,
    safe_cast(cobranca_ingresso as boolean) cobranca_ingresso,
    safe_cast(estrutura as boolean) estrutura,
    safe_cast(manipulacao_alimentos as boolean) manipulacao_alimentos,
    safe_cast(filmagem as boolean) filmagem,
    safe_cast(reserva_vagas as boolean) reserva_vagas,
    safe_cast(tipo_estrutura as string) tipo_estrutura,
    safe_cast(descricao_evento as string) descricao_evento,
    safe_cast(data_evento_inicio as date) data_evento_inicio,
    safe_cast(data_evento_fim as date) data_evento_fim,
    safe_cast(datas_montagem_estrutura as string) datas_montagem_estrutura,
    safe_cast(datas_desmontagem_estrutura as string) datas_desmontagem_estrutura,
    safe_cast(data_abertura_cpe as date) data_abertura_cpe,
    safe_cast(aprovador as string) aprovador,
    safe_cast(decisao_aprovador as string) decisao_aprovador,
    safe_cast(codigo_decisao_aprovador as int64) codigo_decisao_aprovador,
    safe_cast(observacao_aprovador as string) observacao_aprovador,
    safe_cast(orgaos as string) orgaos,
    safe_cast(competencia as string) competencia,
    safe_cast(porta_evento as int64) porta_evento,
    safe_cast(logradouro_evento as string) logradouro_evento,
    safe_cast(estimativa_publica as string) estimativa_publica,
    safe_cast(declaracaoReferenteAVinculoDeRepresentacao as boolean) declaracaoReferenteAVinculoDeRepresentacao,
    safe_cast(certAprovBombeiro as boolean) certAprovBombeiro,
    safe_cast(plantaArea as boolean) plantaArea,
    safe_cast(declaEntreDocVerdadeiro as boolean) declaEntreDocVerdadeiro,
    safe_cast(decContratServLimpeza as boolean) decContratServLimpeza,
    safe_cast(decInstBanheirosQuimicos as boolean) decInstBanheirosQuimicos,
    safe_cast(declaracaoNormasEstaduaisSeguran as boolean) declaracaoNormasEstaduaisSeguran,
    safe_cast(contratoSeguranca as boolean) contratoSeguranca,
    safe_cast(declaResponsAmbiental as boolean) declaResponsAmbiental,
    safe_cast(decRealizEventoSMF as boolean) decRealizEventoSMF,
    safe_cast(aprovSecSMTR as boolean) aprovSecSMTR,
    safe_cast(declaracaoReferenteAsNormasDeSeguranca as boolean) declaracaoReferenteAsNormasDeSeguranca,
    safe_cast(IPHAN as boolean) IPHAN,
    safe_cast(nadaOporSub as boolean) nadaOporSub,
    safe_cast(vigilanciaSanitaria as boolean) vigilanciaSanitaria,
    safe_cast(nenhumDocNece as boolean) nenhumDocNece,
    safe_cast(outros as boolean) outros,
    safe_cast(numero_processo_alvara as string) numero_processo_alvara,
    safe_cast(data_inicio_processo_alvara as date) data_inicio_processo_alvara,
    safe_cast(data_fim_processo_alvara as date) data_fim_processo_alvara,
    safe_cast(data_inicio_processo_cpe as date) data_inicio_processo_cpe,
    safe_cast(data_fim_processo_cpe as date) data_fim_processo_cpe,
    safe_cast(Incide_TLE_cpe as boolean) Incide_TLE_cpe,
    safe_cast(Incide_TUAP_cpe as boolean) Incide_TUAP_cpe,
    safe_cast(Incide_TLE_alvara as boolean) Incide_TLE_alvara,
    safe_cast(Incide_TUAP_alvara as boolean) Incide_TUAP_alvara,
    safe_cast(codigo_TLE_cpe as string) codigo_TLE_cpe,
    safe_cast(titulo_TLE_cpe as string) titulo_TLE_cpe,
    safe_cast(codigo_receita_TLE_cpe as string) codigo_receita_TLE_cpe,
    safe_cast(data_emissao_TLE_cpe as date) data_emissao_TLE_cpe,
    safe_cast(taxa_liberada_TLE_cpe as boolean) taxa_liberada_TLE_cpe,
    safe_cast(valor_TLE_cpe as float64) valor_TLE_cpe,
    safe_cast(competencia_TLE_cpe as string) competencia_TLE_cpe,
    safe_cast(numero_darm_TLE_cpe as string) numero_darm_TLE_cpe,
    safe_cast(inscricao_municipal_TLE_cpe as string) inscricao_municipal_TLE_cpe,
    safe_cast(data_pagamento_TLE_cpe as date) data_pagamento_TLE_cpe,
    safe_cast(data_vencimento_TLE_cpe as date) data_vencimento_TLE_cpe,
    safe_cast(status_TLE_cpe as string) status_TLE_cpe,
    safe_cast(codigo_TUAP_cpe as string) codigo_TUAP_cpe,
    safe_cast(titulo_TUAP_cpe as string) titulo_TUAP_cpe,
    safe_cast(codigo_receita_TUAP_cpe as string) codigo_receita_TUAP_cpe,
    safe_cast(data_emissao_TUAP_cpe as date) data_emissao_TUAP_cpe,
    safe_cast(taxa_liberada_TUAP_cpe as boolean) taxa_liberada_TUAP_cpe,
    safe_cast(valor_TUAP_cpe as float64) valor_TUAP_cpe,
    safe_cast(competencia_TUAP_cpe as string) competencia_TUAP_cpe,
    safe_cast(numero_darm_TUAP_cpe as string) numero_darm_TUAP_cpe,
    safe_cast(inscricao_municipal_TUAP_cpe as string) inscricao_municipal_TUAP_cpe,
    safe_cast(data_pagamento_TUAP_cpe as date) data_pagamento_TUAP_cpe,
    safe_cast(data_vencimento_TUAP_cpe as date) data_vencimento_TUAP_cpe,
    safe_cast(status_TUAP_cpe as string) status_TUAP_cpe,
    safe_cast(codigo_TLE_alvara as string) codigo_TLE_alvara,
    safe_cast(titulo_TLE_alvara as string) titulo_TLE_alvara,
    safe_cast(codigo_receita_TLE_alvara as string) codigo_receita_TLE_alvara,
    safe_cast(data_emissao_TLE_alvara as date) data_emissao_TLE_alvara,
    safe_cast(taxa_liberada_TLE_alvara as boolean) taxa_liberada_TLE_alvara,
    safe_cast(valor_TLE_alvara as float64) valor_TLE_alvara,
    safe_cast(competencia_TLE_alvara as string) competencia_TLE_alvara,
    safe_cast(numero_darm_TLE_alvara as string) numero_darm_TLE_alvara,
    safe_cast(inscricao_municipal_TLE_alvara as string) inscricao_municipal_TLE_alvara,
    safe_cast(data_pagamento_TLE_alvara as date) data_pagamento_TLE_alvara,
    safe_cast(data_vencimento_TLE_alvara as date) data_vencimento_TLE_alvara,
    safe_cast(status_TLE_alvara as string) status_TLE_alvara,
    safe_cast(codigo_TUAP_alvara as string) codigo_TUAP_alvara,
    safe_cast(titulo_TUAP_alvara as string) titulo_TUAP_alvara,
    safe_cast(codigo_receita_TUAP_alvara as string) codigo_receita_TUAP_alvara,
    safe_cast(data_emissao_TUAP_alvara as date) data_emissao_TUAP_alvara,
    safe_cast(taxa_liberada_TUAP_alvara as boolean) taxa_liberada_TUAP_alvara,
    safe_cast(valor_TUAP_alvara as float64) valor_TUAP_alvara,
    safe_cast(competencia_TUAP_alvara as string) competencia_TUAP_alvara,
    safe_cast(numero_darm_TUAP_alvara as string) numero_darm_TUAP_alvara,
    safe_cast(inscricao_municipal_TUAP_alvara as string) inscricao_municipal_TUAP_alvara,
    safe_cast(data_pagamento_TUAP_alvara as date) data_pagamento_TUAP_alvara,
    safe_cast(data_vencimento_TUAP_alvara as date) data_vencimento_TUAP_alvara,
    safe_cast(status_TUAP_alvara as string) status_TUAP_alvara,
        FROM {{ source('brutos_consulta_previa_eventos_staging', 'vw_Consulta_Previa_Eventos') }}