SELECT
  SAFE_CAST(REGEXP_REPLACE(TRIM(id_fornecedor), r'\.0$', '') AS STRING) AS id_fornecedor,
  SAFE_CAST(TRIM(cod_fornecedor) AS STRING) AS cod_fornecedor,
  SAFE_CAST(TRIM(fornecedor) AS STRING) AS fornecedor,
  SAFE_CAST(TRIM(tipo_pessoa) AS STRING) AS tipo_pessoa,
  SAFE_CAST(TRIM(endereco) AS STRING) AS endereco,
  SAFE_CAST(TRIM(numero) AS STRING) AS numero,
  SAFE_CAST(TRIM(complemento) AS STRING) AS complemento,
  SAFE_CAST(TRIM(cep) AS STRING) AS cep,
  SAFE_CAST(TRIM(bairro) AS STRING) AS bairro,
  SAFE_CAST(TRIM(municipio) AS STRING) AS municipio,
  SAFE_CAST(TRIM(uf) AS STRING) AS uf,
  SAFE_CAST(TRIM(referencia) AS STRING) AS referencia,
  SAFE_CAST(TRIM(telefone_1) AS STRING) AS telefone_1,
  SAFE_CAST(TRIM(telefone_1_ramal) AS STRING) AS telefone_1_ramal,
  SAFE_CAST(TRIM(telefone_2) AS STRING) AS telefone_2,
  SAFE_CAST(TRIM(telefone_2_ramal) AS STRING) AS telefone_2_ramal,
  SAFE_CAST(TRIM(telefone_fax) AS STRING) AS telefone_fax,
  SAFE_CAST(TRIM(email) AS STRING) AS email,
  SAFE_CAST(TRIM(contato) AS STRING) AS contato,
  SAFE_CAST(REGEXP_REPLACE(TRIM(id_log_importacao), r'\.0$', '') AS STRING) AS id_log_importacao,
  SAFE_CAST(TRIM(cod_organizacao) AS STRING) AS cod_organizacao,
  SAFE_CAST(SAFE.PARSE_TIMESTAMP('%Y-%m-%d %H:%M:%S', data_envio_data_envio) AS DATETIME) AS data_envio
FROM {{ source('brutos_osinfo_staging', 'fornecedor') }}