{{
    config(
        alias="resposta_ocorrencia",
        materialized='table',
        description="Respostas de ocorrências do sistema Vigia Urbano, contendo informações sobre ocorrências registradas e suas respostas.",
    )
}}

SELECT
    safe_cast(Id AS int64) AS id_resposta_ocorrencia,
    safe_cast(dataHoraRegistro AS datetime) AS data_hora_registro,
    safe_cast(TRIM(logradouro) AS string) AS logradouro,
    safe_cast(TRIM(numeroPorta) AS string) AS numero_porta,
    safe_cast(TRIM(referencia) AS string) AS referencia,
    safe_cast(coordenadaX AS float64) AS coordenada_x,
    safe_cast(coordenadaY AS float64) AS coordenada_y,
    safe_cast(coordenadaXDispositivo AS float64) AS coordenada_x_dispositivo,
    safe_cast(coordenadaYDispositivo AS float64) AS coordenada_y_dispositivo,
    safe_cast(TRIM(observacao) AS string) AS observacao,
    safe_cast(excluido AS bool) AS excluido,
    safe_cast(TRIM(enderecoInformado) AS string) AS endereco_informado,
    safe_cast(TRIM(caminhoImagem) AS string) AS caminho_imagem,
    safe_cast(bairroID AS int64) AS id_bairro,
    safe_cast(TRIM(bairroNome) AS string) AS bairro_nome,
    safe_cast(tipoPessoa AS int64) AS tipo_pessoa,
    safe_cast(TRIM(tipoPessoaDescricao) AS string) AS tipo_pessoa_descricao,
    safe_cast(ocupacaoPessoa AS int64) AS ocupacao_pessoa,
    safe_cast(TRIM(ocupacaoPessoaDescricao) AS string) AS ocupacao_pessoa_descricao,
    safe_cast(tipoFrequencia AS int64) AS tipo_frequencia,
    safe_cast(TRIM(tipoFrequenciaDescricao) AS string) AS tipo_frequencia_descricao,
    safe_cast(ocupacaoDrogas AS int64) AS ocupacao_drogas,
    safe_cast(TRIM(ocupacaoDrogasDescricao) AS string) AS ocupacao_drogas_descricao,
    safe_cast(itemPraca AS int64) AS item_praca,
    safe_cast(TRIM(itemPracaDescricao) AS string) AS item_praca_descricao,
    safe_cast(ocorrenciaID AS int64) AS id_ocorrencia,
    safe_cast(TRIM(ocorrenciaDescricao) AS string) AS ocorrencia_descricao,
    safe_cast(ocorrenciaAtivo AS bool) AS ocorrencia_ativo,
    safe_cast(TRIM(orgaoResponsavel) AS string) AS orgao_responsavel,
    safe_cast(TRIM(quemOpera) AS string) AS quem_opera,
    safe_cast(servico1746 AS bool) AS servico_1746,
    safe_cast(TRIM(ocorrenciaInformacao) AS string) AS ocorrencia_informacao,
    safe_cast(ocorrenciaOrgaoID AS int64) AS id_ocorrencia_orgao,
    safe_cast(TRIM(ocorrenciaOrgaoNome) AS string) AS ocorrencia_orgao_nome,
    safe_cast(TRIM(ocorrenciaOrgaoCodigo) AS string) AS ocorrencia_orgao_codigo,
    safe_cast(categoriaID AS int64) AS id_categoria,
    safe_cast(TRIM(categoriaNome) AS string) AS categoria_nome,
    safe_cast(categoriaAtivo AS bool) AS categoria_ativo,
    safe_cast(usuarioID AS int64) AS id_usuario,
    safe_cast(TRIM(usuarioNome) AS string) AS usuario_nome,
    safe_cast(TRIM(usuarioCpf) AS string) AS usuario_cpf,
    safe_cast(TRIM(usuarioEmail) AS string) AS usuario_email,
    safe_cast(TRIM(usuarioMatricula) AS string) AS usuario_matricula,
    safe_cast(usuarioAtivo AS bool) AS usuario_ativo,
    safe_cast(TRIM(usuarioPerfis) AS string) AS usuario_perfis,
    safe_cast(TRIM(usuarioOrgaoNome) AS string) AS usuario_orgao_nome,
    safe_cast(TRIM(usuarioOrgaoCodigo) AS string) AS usuario_orgao_codigo,
    safe_cast(SUBSTR(_prefect_extracted_at,1,10) as date)          as datalake_loaded_at ,
    safe_cast(CURRENT_TIMESTAMP() AS datetime) AS datalake_transformed_at
FROM {{ source('brutos_formulario_ocorrencia_staging', 'vw_RespostaOcorrencia') }}
