version: 2
models:
  - name: brutos_taxirio__cities
    config:
      alias: cities
    description: "Tabela de Cidades"
    columns:
      - name: id_municipio
        description: "Identificador da cidade"
        data_type: string
        data_tests:
          - not_null
      - name: nome_municipio
        description: "Nome do Municipio"
        data_type: string
      - name: abrev_municipio
        description: "Abreviação do Município"
        data_type: string
      - name: pode_usar_pagamento_app
        description: "Flag se pode usar o pagamento pelo aplicativo (True/ False)"
        data_type: boolean
      - name: calculado_no_app
        description: "Flag se o calculo é pelo aplicativo  (True/ False)"
        data_type: boolean
      - name: forma_de_login
        data_type: string
      - name: estacoes_de_servico
        data_type: json
  - name: brutos_taxirio__discounts
    config:
      alias: discounts
    columns:
      - name: id_desconto_associado
        description: ""
      - name: descricao
        description: ""
      - name: desconto
        description: ""
      - name: data_criacao
        description: ""
  - name: brutos_taxirio__users
    config:
      alias: users
    columns:
      - name: ano_particao
        description: ""
      - name: mes_particao
        description: ""
      - name: dia_particao
        description: ""
      - name: data_criacao
        description: ""
      - name: id_usuario
        description: ""
      - name: sexo
        description: ""
      - name: data_nascimento
        description: ""
  - name: brutos_taxirio__rankingraces
    config:
      alias: rankingraces
    columns:
      - name: ano_particao
        description: ""
      - name: mes_particao
        description: ""
      - name: dia_particao
        description: ""
      - name: data_criacao
        description: ""
      - name: data_atualizacao
        description: ""
      - name: id_ranking_corrida
        description: ""
      - name: id_corrida
        description: ""
      - name: competidores
        description: ""
  - name: brutos_taxirio__paymentmethods
    config:
      alias: paymentmethods
    columns:
      - name: id_pagamento_associado
        description: ""
      - name: pindex
        description: ""
      - name: nome
        description: ""
      - name: tipo
        description: ""
  - name: brutos_taxirio__races
    config:
      alias: races
    colunms:
      - name: ano_particao
        description: ""
      - name: mes_particao
        description: ""
      - name: dia_particao
        description: ""
      - name: data_criacao
        description: ""
      - name: id_corrida
        description: ""
      - name: id_evento
        description: ""
      - name: id_passageiro
        description: ""
      - name: id_municipio
        description: ""
      - name: id_pagamento_associado
        description: ""
      - name: qtd_transmissao
        description: ""
      - name: nota_avaliacao
        description: ""
      - name: suspeito
        description: ""
      - name: invalido
        description: ""
      - name: status
        description: ""
      - name: distancia_rota
        description: ""
      - name: duracao_rota
        description: ""
      - name: valor_estimado
        description: ""
      - name: id_taximetro_associado
        description: ""
      - name: id_tarifa_minima_associada
        description: ""
      - name: id_desconto_associado
        description: ""
      - name: propriedade_corporativa
        description: ""
  - name: brutos_taxirio__passengers
    config:
      alias: passengers
    columns:
      - name: ano_particao
        description: ""
      - name: mes_particao
        description: ""
      - name: dia_particao
        description: ""
      - name: data_criacao
        description: ""
      - name: id_passageiro
        description: ""
      - name: id_usuario
        description: ""
      - name: pode_usar_pagamento_app
        description: ""
      - name: id_phone
        description: ""
      - name: phone_atualizacao
        description: ""
      - name: phone_versao_app
        description: ""
      - name: phone_modelo
        description: ""
      - name: phone_fabricante
        description: ""
      - name: phone_versao_sistema
        description: ""
      - name: phone_nome_sistema
        description: ""
  - name: brutos_taxirio__drivers
    config:
      alias: drivers
    columns:
      - name: ano_particao
        description: ""
      - name: mes_particao
        description: ""
      - name: dia_particao
        description: ""
      - name: data_criacao
        description: ""
      - name: id_motorista
        description: ""
      - name: id_usuario
        description: ""
      - name: id_motorista_taxi
        description: ""
      - name: id_carro_associado
        description: ""
      - name: id_desconto_associado
        description: ""
      - name: id_pagamento_associado
        description: ""
      - name: pode_receber_pagamento_app
        description: ""
      - name: pode_receber_pagamento_prefeitura
        description: ""
      - name: avaliacoes_recebidas
        description: ""
      - name: nota_media
        description: ""
      - name: status
        description: ""
      - name: ocupado
        description: ""
      - name: ultima_nota_media
        description: ""
      - name: id_corrida_bloqueada
        description: ""
      - name: id_municipio
        description: ""
      - name: taxa_servico
        description: ""
      - name: nota
        description: ""
      - name: id_phone
        description: ""
      - name: phone_atualizacao
        description: ""
      - name: phone_versao_app
        description: ""
      - name: phone_modelo
        description: ""
      - name: phone_fabricante
        description: ""
      - name: phone_versao_sistema
        description: ""
      - name: phone_nome_sistema
        description: ""
      - name: corrida_origem_posicao_lng
        description: ""
      - name: corrida_origem_posicao_lat
        description: ""
      - name: id_corrida
        description: ""
      - name: data_bloqueio_espirado
