{{
    config(
        schema='forca_municipal',
        alias="ocorrencias_historico",
        materialized='table',
    )
}}

SELECT
    SAFE_CAST(AddedTime AS TIMESTAMP) AS data_hora_insercao_sistema,
    SAFE_CAST(AgencyEventId AS STRING) AS id_ocorrencia,
    SAFE_CAST(AgencyEventSubtypeCode AS STRING) AS codigo_subtipo_ocorrencia,
    SAFE_CAST(AgencyEventSubtypeCodeDesc AS STRING) AS descricao_subtipo_ocorrencia,
    SAFE_CAST(AgencyEventTypeCode AS STRING) AS codigo_tipo_ocorrencia,
    SAFE_CAST(AgencyEventTypeCodeDesc AS STRING) AS descricao_tipo_ocorrencia,
    SAFE_CAST(AgencyId AS STRING) AS id_agencia,
    SAFE_CAST(AlarmLevel AS INT64) AS nivel_prioridade_alarme,
    SAFE_CAST(Area AS STRING) AS area,
    SAFE_CAST(Attributes AS INT64) AS atributos_flags,
    SAFE_CAST(Beat AS STRING) AS setor_patrulhamento,
    SAFE_CAST(ClosingComment AS STRING) AS comentario_encerramento,
    SAFE_CAST(ClosingEmployeeId AS STRING) AS id_funcionario_encerramento,
    SAFE_CAST(ClosingTime AS TIMESTAMP) AS data_hora_encerramento,
    SAFE_CAST(CreatedEmployeeId AS INT64) AS id_funcionario_criacao,
    SAFE_CAST(CreatedTime AS TIMESTAMP) AS data_hora_criacao,
    SAFE_CAST(CustomData_Estado AS STRING) AS custom_data_estado,
    SAFE_CAST(DatabaseInsertTime AS TIMESTAMP) AS data_hora_insercao_banco,
    SAFE_CAST(DispatchGroup AS STRING) AS grupo_despacho,
    SAFE_CAST(District AS STRING) AS bairro,
    SAFE_CAST(Esz AS INT64) AS codigo_zona_servico_emergencial,
    SAFE_CAST(EventDescription AS STRING) AS descricao_ocorrencia,
    SAFE_CAST(IsOpen AS BOOL) AS indicador_ocorrencia_aberta,
    SAFE_CAST(IsReopened AS BOOL) AS indicador_ocorrencia_reaberta,
    SAFE_CAST(LastStatusChangeTime AS TIMESTAMP) AS data_hora_ultima_alteracao_status,
    SAFE_CAST(Municipality AS STRING) AS municipio,
    SAFE_CAST(OriginalEmployeeId AS INT64) AS id_funcionario_original,
    SAFE_CAST(PendingAlarmTime AS TIMESTAMP) AS data_hora_alarme_pendente,
    SAFE_CAST("Priority" AS INT64) AS nivel_prioridade,
    SAFE_CAST(PriorityChangedTime AS TIMESTAMP) AS data_hora_alteracao_prioridade,
    SAFE_CAST(RevisionEmployeeId AS INT64) AS id_funcionario_revisao,
    SAFE_CAST(RevisionNumber AS INT64) AS numero_revisao,
    SAFE_CAST(RevisionTime AS TIMESTAMP) AS data_hora_revisao,
    SAFE_CAST(StartedTime AS TIMESTAMP) AS data_hora_inicio,
    SAFE_CAST(StatusCode AS INT64) AS codigo_status,
    SAFE_CAST(SubstatusCode AS INT64) AS codigo_substatus,
    SAFE_CAST(TotalAssignedUnits AS INT64) AS total_viaturas_atribuidas,
    SAFE_CAST(UserDefinedSupplementalInfo AS INT64) AS informacoes_suplementares_usuario,
    SAFE_CAST(UserGroupId AS INT64) AS id_grupo_usuarios,
    SAFE_CAST("Zone" AS STRING) AS zona_geografica
FROM {{ source('brutos_forca_municipal_staging', 'ocorrencias_historico') }}
