{{
    config(
        alias='prontuario'
    )
}}

SELECT safe_cast(US AS STRING) AS us, 
safe_cast(CAT AS STRING) AS cat, 
safe_cast(APTO AS STRING) AS apto, 
safe_cast(CHAVE AS STRING) AS chave, 
safe_cast(DTFIM AS DATE) AS dt_fim, 
safe_cast(DTINI AS DATE) AS dt_ini, 
safe_cast(SIGLA AS STRING) AS sigla, 
safe_cast(ID_REG AS STRING) AS id_reg, 
safe_cast(NUMDEP AS STRING) AS numdep, 
safe_cast(DTATEND AS DATE) AS dt_atend, 
safe_cast(NUMFUNC AS STRING) AS numfunc, 
safe_cast(NUMPENS AS STRING) AS numpens, 
safe_cast(NUMPROC AS STRING) AS numproc, 
safe_cast(TP_CID1 AS STRING) AS tp_cid1, 
safe_cast(TP_CID2 AS STRING) AS tp_cid2, 
safe_cast(TP_CID3 AS STRING) AS tp_cid3, 
safe_cast(ANAMNESE AS STRING) AS anamnese, 
safe_cast(CHAVEANT AS STRING) AS chaveant, 
safe_cast(COD_CID1 AS STRING) AS cod_cid1, 
safe_cast(COD_CID2 AS STRING) AS cod_cid2, 
safe_cast(COD_CID3 AS STRING) AS cod_cid3, 
safe_cast(DT_HOMOL AS DATE) AS dt_homol, 
safe_cast(INSCRITO AS STRING) AS inscrito, 
safe_cast(PONTPUBL AS STRING) AS ponto_publicado, 
safe_cast(TIPO_LIC AS STRING) AS tipo_lic, 
safe_cast(CRM_ATEST AS STRING) AS crm_atest, 
safe_cast(CRM_HOMOL AS STRING) AS crm_homol, 
safe_cast(EXAMEADIC AS STRING) AS exameadic, 
safe_cast(EXAM_TEXT AS STRING) AS exam_text, 
safe_cast(HORAATEND AS STRING) AS horaatend, 
safe_cast(TEXTO_AUT AS STRING) AS texto_aut, 
safe_cast(ATEST_PUBL AS STRING) AS atest_publicado, 
safe_cast(CHAVEATEND AS STRING) AS chaveatend, 
safe_cast(REQPERICIA AS STRING) AS reqpericia, 
safe_cast(DTCONCLUSAO AS DATE) AS dtconclusao, 
safe_cast(NOMEPARENTE AS STRING) AS nomeparente, 
safe_cast(COD_ACIDENTE AS STRING) AS cod_acidente, 
safe_cast(NUMVINC_PENS AS STRING) AS numvinc_pens, 
safe_cast(TEXTO_MEDICO AS STRING) AS texto_medico, 
safe_cast(FLEX_CAMPO_01 AS STRING) AS flex_campo_01, 
safe_cast(FLEX_CAMPO_02 AS STRING) AS flex_campo_02, 
safe_cast(FLEX_CAMPO_03 AS STRING) AS flex_campo_03, 
safe_cast(FLEX_CAMPO_04 AS STRING) AS flex_campo_04, 
safe_cast(FLEX_CAMPO_05 AS STRING) AS flex_campo_05,
safe_cast(FLEX_CAMPO_06 AS STRING) AS flex_campo_06, 
safe_cast(FLEX_CAMPO_07 AS STRING) AS flex_campo_07,    
_airbyte_extracted_at as datalake_loaded_at, 
current_timestamp() as datalake_transformed_at   
FROM  {{ source('brutos_recursos_humanos_ergon_pericia_medica_staging', 'PRONTUARIO') }}

