{{
  config(
    materialized='table',
    alias='alvara_obra_privada')
}}

SELECT
CAST(CAST(num_lic AS FLOAT64) AS int64) AS id_licenciamento,
licenca AS numero_alvara_licenca,
num_proc AS numero_processo,
cod_dlf AS id_orgao_sislic,
CAST(dt_emissao AS DATETIME) AS data_emissao,
CAST(dt_inicio_validade AS DATETIME) AS data_inicio_validade,
CAST(dt_venc AS DATETIME) AS data_vencimento,
CAST(CAST(prazo AS FLOAT64) AS int64) AS prazo,
CAST(Dt_alvara AS DATETIME) AS data_passe_alvara,
num_darm_pg AS numero_darm_pago,
CAST(vl_lic AS float64) AS valor_darm,
requerente AS requerente,
cnpj_cpf AS cnpj_cpf,
clogra AS id_logra,
tipo AS tipo_logradouro,
nobreza AS nobreza_logradouro,
preposicao AS preposicao_logradouro,
nomelogra AS nome_logradouro,
num AS numero_porta,
complemento AS complemento_numero_porta,
paa AS paa,
pal AS pal,
plt AS plt,
quadra AS quadra,
lote AS lote,
cb AS centro_bairro,
zona AS zona,
subzona AS subzona,
cep AS cep,
bsmp AS cod_bairro,
num_suple AS numero_logradouro_suplementar,
inscricaoimovel AS inscricao_imovel,
id_tpinscricaoimovel AS id_tipo_inscricao_imovel,
uso_atividade AS uso_atividade,
implantacao AS implantacao,
CAST(CAST(tot_edif AS FLOAT64) AS int64) AS total_edificacoes,
CAST(area_constr AS FLOAT64) AS area_construida,
CAST(area_acrescida AS FLOAT64) AS area_acrescida,
CAST(area_reduzida AS FLOAT64) AS area_reduzida,
CAST(area_util AS FLOAT64) AS area_util,
CAST(area_total_edificada AS FLOAT64) AS area_total_edificada,
CAST(area_existente_declarada_responsavel AS BOOL) AS area_existente_declarada_responsavel,
CAST(areatotal_loteamento AS FLOAT64) AS area_total_loteamento,
CAST(metroslineares_obrasurbanizacao AS FLOAT64) AS metros_lineares_obras_urbanizacao,
CAST(CAST(vagasexternasdescobertas AS FLOAT64) AS INT64) AS vagas_externas_descobertas,
CAST(CAST(vagasexternascobertas AS FLOAT64) AS INT64) AS vagas_externas_cobertas,
CAST(CAST(vagaspavimentos AS FLOAT64) AS INT64) AS vagas_pavimentos,
nome_preo AS nome_preo,
crea_preo AS crea_preo,
rrt_art_preo AS rrt_art_preo,
nome_prpa AS nome_prpa,
crea_prpa AS crea_prpa,
rrt_art_prpa AS rrt_art_prpa,
CAST(grupamento AS BOOL) AS grupamento,
CAST(tot_etapas AS FLOAT64) AS total_etapas,
CAST(tot_edif_etapa AS FLOAT64) AS total_edificacoes_etapa,
CAST(area_tot_etapa AS FLOAT64) AS area_total_etapa,
lic_concedida AS licenca_concedida,
edif_pav AS descricao_edificacao_concatenada,
CAST(concedenumeracao AS bool) AS concede_numeracao,
numconcedida AS numeracao_concedida,
obs AS observacao,
CAST(CAST(mat_func AS FLOAT64) AS INT64) AS matricula_tecnico,
CAST(cancelado AS BOOL) AS cancelado,
CAST(licgratis AS BOOL) AS licenca_gratis,
CAST(orgaocentral AS BOOL) AS licenca_orgao_central,
codorgao_especial AS cod_orgao_especial,
OrdemEmissao AS ordem_emissao,
CAST(licenca_loteamento AS BOOL) AS licenca_loteamento,
CAST(licencaavulsa AS BOOL) AS licenca_avulsa,
CAST(loteamentonovomodelo AS BOOL) AS loteamento_novo_modelo,
CAST(aprovacaoparcelamento AS BOOL) AS aprovacao_parcelamento,
CAST(CAST(totalunidades AS FLOAT64) AS INT64) AS total_unidades,
CAST(CAST(liconline_id_requerimento AS FLOAT64) AS INT64) AS id_requerimento_licenca_online,

FROM {{ source('adm_licenca_urbanismo_staging', 'alvara_obra_privada') }}
