name: dbt-checkpoint

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  dbt-checkpoint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - id: Get file changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: " "

      - name: Install dbt
        run: python -m pip install dbt-core dbt-bigquery

      - name: Set up keyfile for dbt
        run: 'echo "$KEYFILE" > ./.gcloud/dbt-service-account.json'
        shell: bash
        env:
          KEYFILE: ${{secrets.CREDENTIALS}}

